allow-flight=false
allow-nether=false
difficulty=peaceful
enable-command-block=false
enable-rcon=false
enforce-whitelist=true
force-gamemode=true
gamemode=survival
generate-structures=false
hardcore=false
level-name=world
level-seed=774042
level-type=minecraft:flat
max-players=2
motd=Clankie frozen verifier laboratory
online-mode=false
pvp=false
server-ip=127.0.0.1
server-port=25574
spawn-animals=false
spawn-monsters=false
spawn-npcs=false
spawn-protection=0
view-distance=4
white-list=true
