import { mkdtemp, mkdir, readFile, realpath, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { expect, it } from "vitest";
import { installHarnessBridges } from "../src/harness-install.ts";

it.each(["refuse", "native", "symlink", "generated", "source"])(
  "uses consent and preserves source-owned Codex configuration: %s",
  async (kind) => {
    const home = await mkdtemp(join(tmpdir(), "clankie-harness-install-"));
    const calls: { command: string; args: readonly string[] }[] = [];
    const source = join(home, "source.toml");
    const config = join(home, ".codex", "config.toml");
    await mkdir(join(home, ".codex"));
    const contents = kind === "generated" ? "# generated; do not edit\n" : "model = 'owner-choice'\n";
    await writeFile(source, contents);
    if (["symlink", "source"].includes(kind)) await symlink(source, config);
    else await writeFile(config, contents);
    try {
      const results = await installHarnessBridges({
        prepareSkills: async () => {},
        repoRoot: "/fixture/clankie",
        env: { HOME: home },
        consent: async () => kind !== "refuse",
        execute: async (command, args) => {
          calls.push({ command, args });
        },
        ...(kind === "source" ? { codexSourceSetup: { command: "/owner/setup", args: ["codex"] } } : {}),
      });
      expect(results.find((result) => result.harness === "codex")?.status).toBe(
        kind === "refuse"
          ? "declined"
          : ["symlink", "generated"].includes(kind)
            ? "source-manager-required"
            : kind === "source"
              ? "source-setup-completed"
              : "installed",
      );
      if (kind === "refuse") expect(calls.every((call) => call.args[0] === "--version")).toBe(true);
      if (["symlink", "generated", "source"].includes(kind))
        expect(calls.filter((call) => call.command === "codex")).toEqual([
          { command: "codex", args: ["--version"] },
        ]);
      if (kind === "source") expect(calls).toContainEqual({ command: "/owner/setup", args: ["codex"] });
      if (kind === "native")
        expect(calls).toContainEqual({
          command: "codex",
          args: ["plugin", "add", "clankie-worker@clankie-fleet", "--json"],
        });
      expect(await readFile(config, "utf8")).toBe(contents);
      if (["symlink", "source"].includes(kind)) expect(await realpath(config)).toBe(await realpath(source));
    } finally {
      await rm(home, { recursive: true, force: true });
    }
  },
);

it("refuses a configuration swap while the owner is reviewing consent", async () => {
  const home = await mkdtemp(join(tmpdir(), "clankie-harness-race-"));
  const config = join(home, ".codex", "config.toml");
  await mkdir(join(home, ".codex"));
  await writeFile(config, "# original\n");
  const calls: string[] = [];
  try {
    const result = await installHarnessBridges({
      prepareSkills: async () => {},
      repoRoot: "/fixture",
      env: { HOME: home },
      execute: async (command, args) => {
        calls.push(`${command} ${args.join(" ")}`);
      },
      consent: async (harness) => {
        if (harness === "codex") await writeFile(config, "# generated by owner setup\n");
        return harness === "codex";
      },
    });
    expect(result.find((entry) => entry.harness === "codex")).toMatchObject({
      status: "failed",
      detail: expect.stringContaining("changed during consent"),
    });
    expect(calls.filter((call) => call.startsWith("codex plugin"))).toEqual([]);
    expect(await readFile(config, "utf8")).toContain("generated by owner setup");
  } finally {
    await rm(home, { recursive: true, force: true });
  }
});
