import { spawn } from "node:child_process";
import { mkdir, mkdtemp, realpath, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { afterEach, expect, it } from "vitest";

const repo = resolve(import.meta.dirname, "../../..");
const roots: string[] = [];
interface SetupResult {
  transcript: string;
  ok: boolean;
  error?: string;
  calls: Array<{ command: string; args: string[] }>;
  writes: Array<Record<string, unknown>>;
  sourceSetup: string;
  root: string;
}
afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

async function interactiveSetup(
  operation: "install" | "refresh" | "prepare" | "retarget",
  answer: string,
): Promise<SetupResult> {
  const root = await realpath(await mkdtemp(join(tmpdir(), "machine-setup-approval-")));
  roots.push(root);
  const script = join(root, "approval.mjs");
  const moduleUrl = (path: string) => JSON.stringify(pathToFileURL(join(repo, path)).href);
  await mkdir(join(root, ".codex"));
  await writeFile(
    script,
    String.raw`import { symlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { SettingsStore } from ${moduleUrl("packages/settings/src/index.ts")};
import { createFleetSettingsRoutes } from ${moduleUrl("apps/clankie/src/fleet-settings-routes.ts")};
import { runHarnessCommand } from ${moduleUrl("apps/tui/src/command/harness.ts")};
import { runRuntimeCommand } from ${moduleUrl("apps/tui/src/command/runtime.ts")};
const root = process.argv[2], operation = process.argv[3];
const settings = new SettingsStore(join(root, "settings.json"));
await settings.update(current => ({ ...current, autonomy: {fleet:{closure:"lead",machineSetup:"owner"}},
  ...(operation === "retarget" ? {machines:[{id:"pc",ssh:"fixture",shell:"posix",aliases:[]}],execution:{...current.execution,connections:[{id:"pc",machine:"pc",kind:"herdr",session:"fixture",ssh:{host:"original",shell:"posix"},capabilities:["code"],enabled:true}]}} : {}),
  projects:{projects:[{id:"garden",name:"Garden",workspaces:[{id:"primary",machineId:"local",platform:"posix",path:root}]}]} }));
const source = join(root, "codex-source.toml"), sourceSetup = join(root, "owner-source.py");
await writeFile(source, '# generated by owner\n[mcp_servers.clankie]\ncommand = "old"\n');
await symlink(source, join(root, ".codex", "config.toml"));
const calls = [], writes = [], revisions = []; let contextReads = 0;
const routes = createFleetSettingsRoutes(async () => true, settings, {
  herdrBinding: () => ({runtime:"external",session:"fixture",socketPath:join(root,"herdr.sock")})
});
const options = {
  repoRoot:root,settings,cwd:root,host:"http://fixture",env:{HOME:root,CODEX_HOME:join(root,".codex"),CLANKIE_OPERATOR_TOKEN:"fixture"},
  fetchImpl:async (input,init) => {
    const url = new URL(String(input));
    if(url.pathname.endsWith("/prepare")) {writes.push(JSON.parse(init.body));return Response.json({ok:true});}
    if(operation === "retarget" && url.pathname.endsWith("fleet-settings/context") && ++contextReads === 2)
      await settings.update(current => ({...current,execution:{...current.execution,connections:current.execution.connections.map(connection=>({...connection,ssh:{host:"replacement",shell:"posix"}}))}}));
    const response = await routes.request(url.pathname+url.search,init);
    if(url.pathname.endsWith("fleet-settings/context")) revisions.push((await response.clone().json()).machine?.targetRevision);
    return response;
  },
  prepareSkills:async () => {},
  // Observe proposed native commands; no harness or source script is executed.
  execute:async (command,args) => {calls.push({command,args});return {stdout:'{"marketplaces":[]}'};}
};
try {
  const result = operation === "prepare" || operation === "retarget"
    ? await runRuntimeCommand(["prepare",operation === "retarget" ? "pc" : "local","--approve","--codex-source-setup",sourceSetup],options)
    : await runHarnessCommand(operation === "refresh" ? ["install","--refresh-linked","--approve"] : ["install","--approve","--codex-source-setup",sourceSetup],options);
  console.log("SETUP_RESULT:"+JSON.stringify({ok:true,result,calls,writes,sourceSetup,root,revisions}));
} catch(error) {console.log("SETUP_RESULT:"+JSON.stringify({ok:false,error:error.message,calls,writes,sourceSetup,root}));}
`,
  );
  return new Promise<SetupResult>((done, fail) => {
    const child = spawn(
      "python3",
      [
        join(import.meta.dirname, "fixtures/conversation-pty.py"),
        process.execPath,
        "--import",
        join(repo, "apps/tui/node_modules/tsx/dist/loader.mjs"),
        script,
        root,
        operation,
      ],
      { cwd: repo, stdio: ["pipe", "pipe", "pipe"] },
    );
    let pending = "",
      transcript = "",
      errors = "",
      answered = false,
      settled = false;
    const timeout = setTimeout(
      () => finish(new Error(`Approval PTY timed out: ${transcript}\n${errors}`)),
      15_000,
    );
    function finish(error?: Error, result?: Record<string, unknown>) {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      child.kill("SIGTERM");
      if (error) fail(error);
      else done({ transcript, ...result } as unknown as SetupResult);
    }
    child.on("error", finish);
    child.stderr.on("data", (chunk) => {
      errors += String(chunk);
    });
    child.on("exit", () => {
      if (!settled) finish(new Error(`Approval PTY exited without a result: ${transcript}\n${errors}`));
    });
    child.stdout.on("data", (chunk) => {
      pending += String(chunk);
      for (;;) {
        const end = pending.indexOf("\n");
        if (end < 0) break;
        const frame = JSON.parse(pending.slice(0, end)) as { data: string };
        pending = pending.slice(end + 1);
        transcript += Buffer.from(frame.data, "base64").toString("utf8");
        if (!answered && transcript.includes("Proceed? [y/N] ")) {
          answered = true;
          child.stdin.write(`${JSON.stringify({ input: `${answer}\n` })}\n`);
        }
        const result = /SETUP_RESULT:([^\r\n]*)\r?\n/u.exec(transcript)?.[1];
        if (result) {
          try {
            finish(undefined, JSON.parse(result));
          } catch (error) {
            finish(error instanceof Error ? error : new Error(String(error)));
          }
        }
      }
    });
  });
}

it.each(["install", "refresh", "prepare"] as const)(
  "requires a real terminal yes before %s can use explicit owner approval",
  async (operation) => {
    const approved = await interactiveSetup(operation, "yes");
    expect(approved.ok, approved.transcript).toBe(true);
    expect(approved.transcript).toContain("Proceed? [y/N]");
    if (operation === "prepare")
      expect(approved.writes).toEqual([
        {
          workingDirectory: approved.root,
          expectedMachineRevision: expect.stringMatching(/^[a-f0-9]{64}$/u),
          projectId: "garden",
          ownerApproved: true,
          codexSourceSetup: approved.sourceSetup,
        },
      ]);
    else if (operation === "install")
      expect(approved.calls).toContainEqual({ command: "python3", args: [approved.sourceSetup] });
    else expect(approved.calls.some((call) => call.args[0] === "--version")).toBe(true);
    const declined = await interactiveSetup(operation, "n");
    expect(declined.ok).toBe(false);
    expect(declined.error).toContain("not approved");
    expect(declined.calls).toEqual([]);
    expect(declined.writes).toEqual([]);
  },
);

it("refuses a remote target rebound during real terminal owner confirmation", async () => {
  const result = await interactiveSetup("retarget", "yes");
  expect(result.ok, result.transcript).toBe(false);
  expect(result.error).toContain("machine changed during approval");
  expect(result.transcript).toContain("Proceed? [y/N]");
  expect(result.calls).toEqual([]);
  expect(result.writes).toEqual([]);
});
