# Provider-owned Linear SDK SDL subset; provenance and retained scope: README.md

schema {
  query: Query
  mutation: Mutation
}

input ActivityCollectionFilter {
  and: [ActivityCollectionFilter!]
  createdAt: DateComparator
  every: ActivityFilter
  id: IDComparator
  length: NumberComparator
  or: [ActivityCollectionFilter!]
  some: ActivityFilter
  updatedAt: DateComparator
  user: UserFilter
}

input ActivityFilter {
  and: [ActivityFilter!]
  createdAt: DateComparator
  id: IDComparator
  or: [ActivityFilter!]
  updatedAt: DateComparator
  user: UserFilter
}

interface ArchivePayload {
  lastSyncId: Float!
  success: Boolean!
}

input AssigneeSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input AttachmentCollectionFilter {
  and: [AttachmentCollectionFilter!]
  createdAt: DateComparator
  creator: NullableUserFilter
  every: AttachmentFilter
  id: IDComparator
  length: NumberComparator
  or: [AttachmentCollectionFilter!]
  some: AttachmentFilter
  sourceType: SourceTypeComparator
  subtitle: NullableStringComparator
  title: StringComparator
  updatedAt: DateComparator
  url: StringComparator
}

input AttachmentCreateInput {
  commentBody: String
  commentBodyData: JSONObject
  createAsUser: String
  displayIconUrl: String
  groupBySource: Boolean
  iconUrl: String
  id: String
  issueId: String!
  metadata: JSONObject
  subtitle: String
  title: String!
  url: String!
}

input AttachmentFilter {
  and: [AttachmentFilter!]
  createdAt: DateComparator
  creator: NullableUserFilter
  id: IDComparator
  or: [AttachmentFilter!]
  sourceType: SourceTypeComparator
  subtitle: NullableStringComparator
  title: StringComparator
  updatedAt: DateComparator
  url: StringComparator
}

type AttachmentPayload {
  success: Boolean!
}

input BooleanComparator {
  eq: Boolean
  neq: Boolean
}

type Comment implements Node {
  body: String!
  createdAt: DateTime!
  id: ID!
  issue: Issue
  parent: Comment
  project: Project
  projectUpdate: ProjectUpdate
  quotedText: String
  updatedAt: DateTime!
  url: String!
  user: User
}

input CommentCollectionFilter {
  and: [CommentCollectionFilter!]
  body: StringComparator
  createdAt: DateComparator
  documentContent: NullableDocumentContentFilter
  every: CommentFilter
  id: IDComparator
  initiative: NullableInitiativeFilter
  initiativeUpdate: NullableInitiativeUpdateFilter
  issue: NullableIssueFilter
  length: NumberComparator
  needs: CustomerNeedCollectionFilter
  or: [CommentCollectionFilter!]
  parent: NullableCommentFilter
  project: NullableProjectFilter
  projectUpdate: NullableProjectUpdateFilter
  reactions: ReactionCollectionFilter
  some: CommentFilter
  updatedAt: DateComparator
  user: UserFilter
}

type CommentConnection {
  nodes: [Comment!]!
  pageInfo: PageInfo!
}

input CommentCreateInput {
  body: String
  bodyData: JSON
  createAsUser: String
  createOnSyncedSlackThread: Boolean
  createdAt: DateTime
  displayIconUrl: String
  doNotSubscribeToIssue: Boolean
  documentContentId: String
  id: String
  initiativeId: String
  initiativeUpdateId: String
  issueId: String
  parentId: String
  postId: String
  projectId: String
  projectUpdateId: String
  quotedText: String
  subscriberIds: [String!]
}

input CommentFilter {
  and: [CommentFilter!]
  body: StringComparator
  createdAt: DateComparator
  documentContent: NullableDocumentContentFilter
  id: IDComparator
  initiative: NullableInitiativeFilter
  initiativeUpdate: NullableInitiativeUpdateFilter
  issue: NullableIssueFilter
  needs: CustomerNeedCollectionFilter
  or: [CommentFilter!]
  parent: NullableCommentFilter
  project: NullableProjectFilter
  projectUpdate: NullableProjectUpdateFilter
  reactions: ReactionCollectionFilter
  updatedAt: DateComparator
  user: UserFilter
}

type CommentPayload {
  comment: Comment!
  success: Boolean!
}

input CommentUpdateInput {
  body: String
  bodyData: JSON
  doNotSubscribeToIssue: Boolean
  quotedText: String
  resolvingCommentId: String
  resolvingUserId: String
  subscriberIds: [String!]
}

input CompletedAtSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input ContentComparator {
  contains: String
  notContains: String
}

input CreatedAtSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input CustomerCountSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input CustomerImportantCountSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input CustomerNeedCollectionFilter {
  and: [CustomerNeedCollectionFilter!]
  comment: NullableCommentFilter
  createdAt: DateComparator
  customer: NullableCustomerFilter
  every: CustomerNeedFilter
  id: IDComparator
  issue: NullableIssueFilter
  length: NumberComparator
  or: [CustomerNeedCollectionFilter!]
  priority: NumberComparator
  project: NullableProjectFilter
  some: CustomerNeedFilter
  updatedAt: DateComparator
}

input CustomerNeedFilter {
  and: [CustomerNeedFilter!]
  comment: NullableCommentFilter
  createdAt: DateComparator
  customer: NullableCustomerFilter
  id: IDComparator
  issue: NullableIssueFilter
  or: [CustomerNeedFilter!]
  priority: NumberComparator
  project: NullableProjectFilter
  updatedAt: DateComparator
}

input CustomerRevenueSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input CustomerSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input CustomerStatusFilter {
  and: [CustomerStatusFilter!]
  color: StringComparator
  createdAt: DateComparator
  description: StringComparator
  id: IDComparator
  name: StringComparator
  or: [CustomerStatusFilter!]
  position: NumberComparator
  type: StringComparator
  updatedAt: DateComparator
}

input CustomerTierFilter {
  and: [CustomerTierFilter!]
  color: StringComparator
  createdAt: DateComparator
  description: StringComparator
  displayName: StringComparator
  id: IDComparator
  or: [CustomerTierFilter!]
  position: NumberComparator
  updatedAt: DateComparator
}

input CycleFilter {
  and: [CycleFilter!]
  completedAt: DateComparator
  createdAt: DateComparator
  endsAt: DateComparator
  id: IDComparator
  inheritedFromId: IDComparator
  isActive: BooleanComparator
  isFuture: BooleanComparator
  isInCooldown: BooleanComparator
  isNext: BooleanComparator
  isPast: BooleanComparator
  isPrevious: BooleanComparator
  issues: IssueCollectionFilter
  name: StringComparator
  number: NumberComparator
  or: [CycleFilter!]
  startsAt: DateComparator
  team: TeamFilter
  updatedAt: DateComparator
}

enum CyclePeriod {
  after
  before
  during
}

input CyclePeriodComparator {
  eq: CyclePeriod
  in: [CyclePeriod!]
  neq: CyclePeriod
  nin: [CyclePeriod!]
  null: Boolean
}

input CycleSort {
  currentCycleFirst: Boolean = false
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input DateComparator {
  eq: DateTimeOrDuration
  gt: DateTimeOrDuration
  gte: DateTimeOrDuration
  in: [DateTimeOrDuration!]
  lt: DateTimeOrDuration
  lte: DateTimeOrDuration
  neq: DateTimeOrDuration
  nin: [DateTimeOrDuration!]
}

enum DateResolutionType {
  halfYear
  month
  quarter
  year
}

scalar DateTime

scalar DateTimeOrDuration

enum Day {
  Friday
  Monday
  Saturday
  Sunday
  Thursday
  Tuesday
  Wednesday
}

input DelegateSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

type Document implements Node {
  id: ID!
  title: String!
  url: String!
}

type DocumentArchivePayload implements ArchivePayload {
  lastSyncId: Float!
  success: Boolean!
}

type DocumentConnection {
  nodes: [Document!]!
  pageInfo: PageInfo!
}

input DocumentFilter {
  and: [DocumentFilter!]
  createdAt: DateComparator
  creator: UserFilter
  cycle: CycleFilter
  id: IDComparator
  initiative: InitiativeFilter
  issue: IssueFilter
  or: [DocumentFilter!]
  owner: NullableUserFilter
  project: ProjectFilter
  release: ReleaseFilter
  searchableContent: ContentComparator
  slugId: StringComparator
  team: NullableTeamFilter
  title: StringComparator
  updatedAt: DateComparator
}

input DueDateSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

scalar Duration

type EntityExternalLink implements Node {
  id: ID!
  label: String!
  url: String!
}

type EntityExternalLinkConnection {
  nodes: [EntityExternalLink!]!
  pageInfo: PageInfo!
}

input EntityExternalLinkCreateInput {
  cycleId: String
  id: String
  initiativeId: String
  label: String!
  projectId: String
  releaseId: String
  resourceFolderId: String
  sortOrder: Float
  teamId: String
  url: String!
}

type EntityExternalLinkPayload {
  success: Boolean!
}

input EntityIdentifierIDComparator {
  eq: ID
  in: [ID!]
  neq: ID
  nin: [ID!]
}

input EstimateComparator {
  and: [NullableNumberComparator!]
  eq: Float
  gt: Float
  gte: Float
  in: [Float!]
  lt: Float
  lte: Float
  neq: Float
  nin: [Float!]
  null: Boolean
  or: [NullableNumberComparator!]
}

input EstimateSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

enum FrequencyResolutionType {
  daily
  weekly
}

input IDComparator {
  eq: ID
  in: [ID!]
  neq: ID
  nin: [ID!]
}

type Initiative implements Node {
  id: ID!
  name: String!
  projects(after: String, before: String, filter: ProjectFilter, first: Int, includeArchived: Boolean, includeSubInitiatives: Boolean, last: Int, orderBy: PaginationOrderBy, sort: [ProjectSortInput!]): ProjectConnection!
  status: InitiativeStatus!
  targetDate: TimelessDate
}

input InitiativeCollectionFilter {
  activityType: StringComparator
  ancestors: InitiativeCollectionFilter
  and: [InitiativeCollectionFilter!]
  canceledAt: NullableDateComparator
  completedAt: NullableDateComparator
  createdAt: DateComparator
  creator: NullableUserFilter
  customIdentifier: NullableStringComparator
  every: InitiativeFilter
  health: StringComparator
  healthWithAge: StringComparator
  id: EntityIdentifierIDComparator
  initiativeUpdates: InitiativeUpdatesCollectionFilter
  labels: InitiativeLabelCollectionFilter
  leadTeam: NullableTeamFilter
  length: NumberComparator
  name: StringComparator
  or: [InitiativeCollectionFilter!]
  owner: NullableUserFilter
  priority: NullableNumberComparator
  projects: ProjectCollectionFilter
  slugId: StringComparator
  some: InitiativeFilter
  startedAt: NullableDateComparator
  status: StringComparator
  targetDate: NullableDateComparator
  teams: TeamCollectionFilter
  updatedAt: DateComparator
}

type InitiativeConnection {
  nodes: [Initiative!]!
  pageInfo: PageInfo!
}

input InitiativeCreatedAtSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input InitiativeFilter {
  activityType: StringComparator
  ancestors: InitiativeCollectionFilter
  and: [InitiativeFilter!]
  canceledAt: NullableDateComparator
  completedAt: NullableDateComparator
  createdAt: DateComparator
  creator: NullableUserFilter
  customIdentifier: NullableStringComparator
  health: StringComparator
  healthWithAge: StringComparator
  id: EntityIdentifierIDComparator
  initiativeUpdates: InitiativeUpdatesCollectionFilter
  labels: InitiativeLabelCollectionFilter
  leadTeam: NullableTeamFilter
  name: StringComparator
  or: [InitiativeFilter!]
  owner: NullableUserFilter
  priority: NullableNumberComparator
  projects: ProjectCollectionFilter
  slugId: StringComparator
  startedAt: NullableDateComparator
  status: StringComparator
  targetDate: NullableDateComparator
  teams: TeamCollectionFilter
  updatedAt: DateComparator
}

input InitiativeHealthSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input InitiativeHealthUpdatedAtSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input InitiativeLabelCollectionFilter {
  and: [InitiativeLabelCollectionFilter!]
  createdAt: DateComparator
  creator: NullableUserFilter
  every: InitiativeLabelFilter
  id: IDComparator
  isGroup: BooleanComparator
  length: NumberComparator
  name: StringComparator
  null: Boolean
  or: [InitiativeLabelCollectionFilter!]
  parent: InitiativeLabelFilter
  some: InitiativeLabelCollectionFilter
  updatedAt: DateComparator
}

input InitiativeLabelFilter {
  and: [InitiativeLabelFilter!]
  createdAt: DateComparator
  creator: NullableUserFilter
  id: IDComparator
  isGroup: BooleanComparator
  name: StringComparator
  or: [InitiativeLabelFilter!]
  parent: InitiativeLabelFilter
  updatedAt: DateComparator
}

input InitiativeManualSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input InitiativeNameSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input InitiativeOwnerSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input InitiativePrioritySort {
  noPriorityFirst: Boolean = false
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input InitiativeSortInput {
  createdAt: InitiativeCreatedAtSort
  health: InitiativeHealthSort
  healthUpdatedAt: InitiativeHealthUpdatedAtSort
  manual: InitiativeManualSort
  name: InitiativeNameSort
  owner: InitiativeOwnerSort
  priority: InitiativePrioritySort
  targetDate: InitiativeTargetDateSort
  updatedAt: InitiativeUpdatedAtSort
}

enum InitiativeStatus {
  Active
  Canceled
  Completed
  Planned
  Proposed
}

input InitiativeTargetDateSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input InitiativeUpdatedAtSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input InitiativeUpdatesCollectionFilter {
  and: [InitiativeUpdatesCollectionFilter!]
  createdAt: DateComparator
  every: InitiativeUpdatesFilter
  id: IDComparator
  length: NumberComparator
  or: [InitiativeUpdatesCollectionFilter!]
  some: InitiativeUpdatesFilter
  updatedAt: DateComparator
}

input InitiativeUpdatesFilter {
  and: [InitiativeUpdatesFilter!]
  createdAt: DateComparator
  id: IDComparator
  or: [InitiativeUpdatesFilter!]
  updatedAt: DateComparator
}

type Issue implements Node {
  assignee: User
  children(after: String, before: String, filter: IssueFilter, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): IssueConnection!
  createdAt: DateTime!
  description: String
  dueDate: TimelessDate
  estimate: Float
  id: ID!
  identifier: String!
  inverseRelations(after: String, before: String, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): IssueRelationConnection!
  labels(after: String, before: String, filter: IssueLabelFilter, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): IssueLabelConnection!
  parent: Issue
  priority: Float!
  project: Project
  projectMilestone: ProjectMilestone
  relations(after: String, before: String, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): IssueRelationConnection!
  state: WorkflowState!
  team: Team!
  title: String!
  updatedAt: DateTime!
  url: String!
}

input IssueCollectionFilter {
  accumulatedStateUpdatedAt: NullableDateComparator
  activity: ActivityCollectionFilter
  addedToCycleAt: NullableDateComparator
  addedToCyclePeriod: CyclePeriodComparator
  ageTime: NullableDurationComparator
  and: [IssueCollectionFilter!]
  archivedAt: NullableDateComparator
  assignee: NullableUserFilter
  attachments: AttachmentCollectionFilter
  autoArchivedAt: NullableDateComparator
  autoClosedAt: NullableDateComparator
  canceledAt: NullableDateComparator
  children: IssueCollectionFilter
  comments: CommentCollectionFilter
  completedAt: NullableDateComparator
  createdAt: DateComparator
  creator: NullableUserFilter
  customerCount: NumberComparator
  customerImportantCount: NumberComparator
  cycle: NullableCycleFilter
  cycleTime: NullableDurationComparator
  delegate: NullableUserFilter
  description: NullableStringComparator
  dueDate: NullableTimelessDateComparator
  estimate: EstimateComparator
  every: IssueFilter
  hasActiveAgentSessions: RelationExistsComparator
  hasBlockedByRelations: RelationExistsComparator
  hasBlockingRelations: RelationExistsComparator
  hasDismissedAgentSessions: RelationExistsComparator
  hasDuplicateRelations: RelationExistsComparator
  hasErroredAgentSessions: RelationExistsComparator
  hasMergedAgentPullRequests: RelationExistsComparator
  hasRelatedRelations: RelationExistsComparator
  hasSharedUsers: RelationExistsComparator
  hasSuggestedAssignees: RelationExistsComparator
  hasSuggestedLabels: RelationExistsComparator
  hasSuggestedProjects: RelationExistsComparator
  hasSuggestedRelatedIssues: RelationExistsComparator
  hasSuggestedSimilarIssues: RelationExistsComparator
  hasSuggestedTeams: RelationExistsComparator
  id: IssueIDComparator
  labels: IssueLabelCollectionFilter
  lastAppliedTemplate: NullableTemplateFilter
  leadTime: NullableDurationComparator
  length: NumberComparator
  needs: CustomerNeedCollectionFilter
  number: NumberComparator
  or: [IssueCollectionFilter!]
  parent: NullableIssueFilter
  priority: NullableNumberComparator
  project: NullableProjectFilter
  projectMilestone: NullableProjectMilestoneFilter
  reactions: ReactionCollectionFilter
  recurringIssueTemplate: NullableTemplateFilter
  releases: ReleaseCollectionFilter
  searchableContent: ContentComparator
  sharedWith: UserCollectionFilter
  slaBreachesAt: NullableDateComparator
  slaStatus: SlaStatusComparator
  snoozedBy: NullableUserFilter
  snoozedUntilAt: NullableDateComparator
  some: IssueFilter
  sourceMetadata: SourceMetadataComparator
  startedAt: NullableDateComparator
  state: WorkflowStateFilter
  subscribers: UserCollectionFilter
  suggestions: IssueSuggestionCollectionFilter
  team: TeamFilter
  title: StringComparator
  triageTime: NullableDurationComparator
  triagedAt: NullableDateComparator
  updatedAt: DateComparator
}

type IssueConnection {
  nodes: [Issue!]!
  pageInfo: PageInfo!
}

input IssueCreateInput {
  assigneeId: String
  completedAt: DateTime
  createAsUser: String
  createdAt: DateTime
  cycleId: String
  delegateId: String
  description: String
  descriptionData: JSON
  displayIconUrl: String
  dueDate: TimelessDate
  estimate: Int
  id: String
  inheritsSharedAccess: Boolean
  labelIds: [String!]
  lastAppliedTemplateId: String
  parentId: String
  preserveSortOrderOnCreate: Boolean
  priority: Int
  prioritySortOrder: Float
  projectId: String
  projectMilestoneId: String
  referenceCommentId: String
  releaseIds: [String!]
  slaBreachesAt: DateTime
  slaStartedAt: DateTime
  slaType: SLADayCountType
  sortOrder: Float
  sourceCommentId: String
  sourcePullRequestCommentId: String
  stateId: String
  subIssueSortOrder: Float
  subscriberIds: [String!]
  teamId: String!
  templateId: String
  title: String
  useDefaultTemplate: Boolean
}

input IssueFilter {
  accumulatedStateUpdatedAt: NullableDateComparator
  activity: ActivityCollectionFilter
  addedToCycleAt: NullableDateComparator
  addedToCyclePeriod: CyclePeriodComparator
  ageTime: NullableDurationComparator
  and: [IssueFilter!]
  archivedAt: NullableDateComparator
  assignee: NullableUserFilter
  attachments: AttachmentCollectionFilter
  autoArchivedAt: NullableDateComparator
  autoClosedAt: NullableDateComparator
  canceledAt: NullableDateComparator
  children: IssueCollectionFilter
  comments: CommentCollectionFilter
  completedAt: NullableDateComparator
  createdAt: DateComparator
  creator: NullableUserFilter
  customerCount: NumberComparator
  customerImportantCount: NumberComparator
  cycle: NullableCycleFilter
  cycleTime: NullableDurationComparator
  delegate: NullableUserFilter
  description: NullableStringComparator
  dueDate: NullableTimelessDateComparator
  estimate: EstimateComparator
  hasActiveAgentSessions: RelationExistsComparator
  hasBlockedByRelations: RelationExistsComparator
  hasBlockingRelations: RelationExistsComparator
  hasDismissedAgentSessions: RelationExistsComparator
  hasDuplicateRelations: RelationExistsComparator
  hasErroredAgentSessions: RelationExistsComparator
  hasMergedAgentPullRequests: RelationExistsComparator
  hasRelatedRelations: RelationExistsComparator
  hasSharedUsers: RelationExistsComparator
  hasSuggestedAssignees: RelationExistsComparator
  hasSuggestedLabels: RelationExistsComparator
  hasSuggestedProjects: RelationExistsComparator
  hasSuggestedRelatedIssues: RelationExistsComparator
  hasSuggestedSimilarIssues: RelationExistsComparator
  hasSuggestedTeams: RelationExistsComparator
  id: IssueIDComparator
  labels: IssueLabelCollectionFilter
  lastAppliedTemplate: NullableTemplateFilter
  leadTime: NullableDurationComparator
  needs: CustomerNeedCollectionFilter
  number: NumberComparator
  or: [IssueFilter!]
  parent: NullableIssueFilter
  priority: NullableNumberComparator
  project: NullableProjectFilter
  projectMilestone: NullableProjectMilestoneFilter
  reactions: ReactionCollectionFilter
  recurringIssueTemplate: NullableTemplateFilter
  releases: ReleaseCollectionFilter
  searchableContent: ContentComparator
  sharedWith: UserCollectionFilter
  slaBreachesAt: NullableDateComparator
  slaStatus: SlaStatusComparator
  snoozedBy: NullableUserFilter
  snoozedUntilAt: NullableDateComparator
  sourceMetadata: SourceMetadataComparator
  startedAt: NullableDateComparator
  state: WorkflowStateFilter
  subscribers: UserCollectionFilter
  suggestions: IssueSuggestionCollectionFilter
  team: TeamFilter
  title: StringComparator
  triageTime: NullableDurationComparator
  triagedAt: NullableDateComparator
  updatedAt: DateComparator
}

input IssueIDComparator {
  eq: ID
  in: [ID!]
  neq: ID
  nin: [ID!]
}

type IssueLabel implements Node {
  color: String!
  description: String
  id: ID!
  isGroup: Boolean!
  name: String!
  parent: IssueLabel
  team: Team
}

input IssueLabelCollectionFilter {
  and: [IssueLabelCollectionFilter!]
  createdAt: DateComparator
  creator: NullableUserFilter
  every: IssueLabelFilter
  id: IDComparator
  isGroup: BooleanComparator
  length: NumberComparator
  name: StringComparator
  null: Boolean
  or: [IssueLabelCollectionFilter!]
  parent: IssueLabelFilter
  some: IssueLabelFilter
  team: NullableTeamFilter
  updatedAt: DateComparator
}

type IssueLabelConnection {
  nodes: [IssueLabel!]!
  pageInfo: PageInfo!
}

input IssueLabelCreateInput {
  color: String
  description: String
  groupType: LabelGroupType
  id: String
  isGroup: Boolean
  name: String!
  parentId: String
  retiredAt: DateTime
  teamId: String
}

input IssueLabelFilter {
  and: [IssueLabelFilter!]
  createdAt: DateComparator
  creator: NullableUserFilter
  id: IDComparator
  isGroup: BooleanComparator
  name: StringComparator
  or: [IssueLabelFilter!]
  parent: IssueLabelFilter
  team: NullableTeamFilter
  updatedAt: DateComparator
}

type IssueLabelPayload {
  issueLabel: IssueLabel!
  success: Boolean!
}

input IssueLabelUpdateInput {
  color: String
  description: String
  groupType: LabelGroupType
  isGroup: Boolean
  name: String
  parentId: String
  retiredAt: DateTime
}

type IssuePayload {
  issue: Issue
  success: Boolean!
}

type IssueRelation implements Node {
  id: ID!
  issue: Issue!
  relatedIssue: Issue!
  type: String!
}

type IssueRelationConnection {
  nodes: [IssueRelation!]!
  pageInfo: PageInfo!
}

input IssueRelationCreateInput {
  id: String
  issueId: String!
  relatedIssueId: String!
  type: IssueRelationType!
}

type IssueRelationPayload {
  success: Boolean!
}

enum IssueRelationType {
  blocks
  duplicate
  related
  similar
}

type IssueSearchPayload {
  nodes: [IssueSearchResult!]!
  pageInfo: PageInfo!
}

type IssueSearchResult implements Node {
  assignee: User
  createdAt: DateTime!
  description: String
  dueDate: TimelessDate
  estimate: Float
  id: ID!
  identifier: String!
  labels(after: String, before: String, filter: IssueLabelFilter, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): IssueLabelConnection!
  parent: Issue
  priority: Float!
  project: Project
  projectMilestone: ProjectMilestone
  state: WorkflowState!
  team: Team!
  title: String!
  updatedAt: DateTime!
  url: String!
}

input IssueSortInput {
  accumulatedStateUpdatedAt: TimeInStatusSort
  assignee: AssigneeSort
  completedAt: CompletedAtSort
  createdAt: CreatedAtSort
  customer: CustomerSort
  customerCount: CustomerCountSort
  customerImportantCount: CustomerImportantCountSort
  customerRevenue: CustomerRevenueSort
  cycle: CycleSort
  delegate: DelegateSort
  dueDate: DueDateSort
  estimate: EstimateSort
  label: LabelSort
  labelGroup: LabelGroupSort
  linkCount: LinkCountSort
  manual: ManualSort
  milestone: MilestoneSort
  priority: PrioritySort
  project: ProjectSort
  release: ReleaseSort
  rootIssue: RootIssueSort
  slaStatus: SlaStatusSort
  team: TeamSort
  title: TitleSort
  updatedAt: UpdatedAtSort
  workflowState: WorkflowStateSort
}

input IssueSuggestionCollectionFilter {
  and: [IssueSuggestionCollectionFilter!]
  createdAt: DateComparator
  every: IssueSuggestionFilter
  id: IDComparator
  length: NumberComparator
  or: [IssueSuggestionCollectionFilter!]
  some: IssueSuggestionFilter
  state: StringComparator
  suggestedLabel: IssueLabelFilter
  suggestedProject: NullableProjectFilter
  suggestedTeam: NullableTeamFilter
  suggestedUser: NullableUserFilter
  type: StringComparator
  updatedAt: DateComparator
}

input IssueSuggestionFilter {
  and: [IssueSuggestionFilter!]
  createdAt: DateComparator
  id: IDComparator
  or: [IssueSuggestionFilter!]
  state: StringComparator
  suggestedLabel: IssueLabelFilter
  suggestedProject: NullableProjectFilter
  suggestedTeam: NullableTeamFilter
  suggestedUser: NullableUserFilter
  type: StringComparator
  updatedAt: DateComparator
}

input IssueUpdateInput {
  addedLabelIds: [String!]
  addedReleaseIds: [String!]
  assigneeId: String
  autoClosedByParentClosing: Boolean
  cycleId: String
  delegateId: String
  description: String
  descriptionData: JSON
  dueDate: TimelessDate
  estimate: Int
  inheritsSharedAccess: Boolean
  labelIds: [String!]
  lastAppliedTemplateId: String
  parentId: String
  priority: Int
  prioritySortOrder: Float
  projectId: String
  projectMilestoneId: String
  releaseIds: [String!]
  removedLabelIds: [String!]
  removedReleaseIds: [String!]
  slaBreachesAt: DateTime
  slaStartedAt: DateTime
  slaType: SLADayCountType
  snoozedById: String
  snoozedUntilAt: DateTime
  sortOrder: Float
  stateId: String
  subIssueSortOrder: Float
  subscriberIds: [String!]
  teamId: String
  title: String
  trashed: Boolean
  trusted: Boolean
}

scalar JSON

scalar JSONObject

input LabelGroupSort {
  labelGroupId: String!
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

enum LabelGroupType {
  multiSelect
  singleSelect
}

input LabelSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input LinkCountSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input ManualSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input MilestoneSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

type Mutation {
  attachmentCreate(input: AttachmentCreateInput!): AttachmentPayload!
  commentCreate(input: CommentCreateInput!): CommentPayload!
  commentUpdate(id: String!, input: CommentUpdateInput!, skipEditedAt: Boolean): CommentPayload!
  documentDelete(id: String!): DocumentArchivePayload!
  entityExternalLinkCreate(input: EntityExternalLinkCreateInput!): EntityExternalLinkPayload!
  issueCreate(input: IssueCreateInput!): IssuePayload!
  issueLabelCreate(input: IssueLabelCreateInput!, replaceTeamLabels: Boolean): IssueLabelPayload!
  issueLabelUpdate(id: String!, input: IssueLabelUpdateInput!, replaceTeamLabels: Boolean): IssueLabelPayload!
  issueRelationCreate(input: IssueRelationCreateInput!, overrideCreatedAt: DateTime): IssueRelationPayload!
  issueUpdate(id: String!, input: IssueUpdateInput!): IssuePayload!
  projectCreate(aiConversationId: String, input: ProjectCreateInput!, projectDraftId: String, slackChannelName: String): ProjectPayload!
  projectUpdate(id: String!, input: ProjectUpdateInput!): ProjectPayload!
  projectUpdateCreate(input: ProjectUpdateCreateInput!): ProjectUpdatePayload!
  projectUpdateUpdate(id: String!, input: ProjectUpdateUpdateInput!): ProjectUpdatePayload!
}

interface Node {
  id: ID!
}

input NullableCommentFilter {
  and: [NullableCommentFilter!]
  body: StringComparator
  createdAt: DateComparator
  documentContent: NullableDocumentContentFilter
  id: IDComparator
  initiative: NullableInitiativeFilter
  initiativeUpdate: NullableInitiativeUpdateFilter
  issue: NullableIssueFilter
  needs: CustomerNeedCollectionFilter
  null: Boolean
  or: [NullableCommentFilter!]
  parent: NullableCommentFilter
  project: NullableProjectFilter
  projectUpdate: NullableProjectUpdateFilter
  reactions: ReactionCollectionFilter
  updatedAt: DateComparator
  user: UserFilter
}

input NullableCustomerFilter {
  and: [NullableCustomerFilter!]
  createdAt: DateComparator
  domains: StringArrayComparator
  externalIds: StringArrayComparator
  id: IDComparator
  name: StringComparator
  needs: CustomerNeedCollectionFilter
  null: Boolean
  or: [NullableCustomerFilter!]
  owner: NullableUserFilter
  revenue: NumberComparator
  size: NumberComparator
  slackChannelId: StringComparator
  status: CustomerStatusFilter
  tier: CustomerTierFilter
  updatedAt: DateComparator
}

input NullableCycleFilter {
  and: [NullableCycleFilter!]
  completedAt: DateComparator
  createdAt: DateComparator
  endsAt: DateComparator
  id: IDComparator
  inheritedFromId: IDComparator
  isActive: BooleanComparator
  isFuture: BooleanComparator
  isInCooldown: BooleanComparator
  isNext: BooleanComparator
  isPast: BooleanComparator
  isPrevious: BooleanComparator
  issues: IssueCollectionFilter
  name: StringComparator
  null: Boolean
  number: NumberComparator
  or: [NullableCycleFilter!]
  startsAt: DateComparator
  team: TeamFilter
  updatedAt: DateComparator
}

input NullableDateComparator {
  eq: DateTimeOrDuration
  gt: DateTimeOrDuration
  gte: DateTimeOrDuration
  in: [DateTimeOrDuration!]
  lt: DateTimeOrDuration
  lte: DateTimeOrDuration
  neq: DateTimeOrDuration
  nin: [DateTimeOrDuration!]
  null: Boolean
}

input NullableDocumentContentFilter {
  and: [NullableDocumentContentFilter!]
  content: NullableStringComparator
  createdAt: DateComparator
  document: DocumentFilter
  id: IDComparator
  initiative: InitiativeFilter
  issue: IssueFilter
  null: Boolean
  or: [NullableDocumentContentFilter!]
  project: ProjectFilter
  projectMilestone: ProjectMilestoneFilter
  updatedAt: DateComparator
}

input NullableDurationComparator {
  eq: Duration
  gt: Duration
  gte: Duration
  in: [Duration!]
  lt: Duration
  lte: Duration
  neq: Duration
  nin: [Duration!]
  null: Boolean
}

input NullableInitiativeFilter {
  activityType: StringComparator
  ancestors: InitiativeCollectionFilter
  and: [NullableInitiativeFilter!]
  canceledAt: NullableDateComparator
  completedAt: NullableDateComparator
  createdAt: DateComparator
  creator: NullableUserFilter
  customIdentifier: NullableStringComparator
  health: StringComparator
  healthWithAge: StringComparator
  id: EntityIdentifierIDComparator
  initiativeUpdates: InitiativeUpdatesCollectionFilter
  labels: InitiativeLabelCollectionFilter
  leadTeam: NullableTeamFilter
  name: StringComparator
  null: Boolean
  or: [NullableInitiativeFilter!]
  owner: NullableUserFilter
  priority: NullableNumberComparator
  projects: ProjectCollectionFilter
  slugId: StringComparator
  startedAt: NullableDateComparator
  status: StringComparator
  targetDate: NullableDateComparator
  teams: TeamCollectionFilter
  updatedAt: DateComparator
}

input NullableInitiativeUpdateFilter {
  and: [NullableInitiativeUpdateFilter!]
  createdAt: DateComparator
  id: IDComparator
  initiative: InitiativeFilter
  null: Boolean
  or: [NullableInitiativeUpdateFilter!]
  reactions: ReactionCollectionFilter
  updatedAt: DateComparator
  user: UserFilter
}

input NullableIssueFilter {
  accumulatedStateUpdatedAt: NullableDateComparator
  activity: ActivityCollectionFilter
  addedToCycleAt: NullableDateComparator
  addedToCyclePeriod: CyclePeriodComparator
  ageTime: NullableDurationComparator
  and: [NullableIssueFilter!]
  archivedAt: NullableDateComparator
  assignee: NullableUserFilter
  attachments: AttachmentCollectionFilter
  autoArchivedAt: NullableDateComparator
  autoClosedAt: NullableDateComparator
  canceledAt: NullableDateComparator
  children: IssueCollectionFilter
  comments: CommentCollectionFilter
  completedAt: NullableDateComparator
  createdAt: DateComparator
  creator: NullableUserFilter
  customerCount: NumberComparator
  customerImportantCount: NumberComparator
  cycle: NullableCycleFilter
  cycleTime: NullableDurationComparator
  delegate: NullableUserFilter
  description: NullableStringComparator
  dueDate: NullableTimelessDateComparator
  estimate: EstimateComparator
  hasActiveAgentSessions: RelationExistsComparator
  hasBlockedByRelations: RelationExistsComparator
  hasBlockingRelations: RelationExistsComparator
  hasDismissedAgentSessions: RelationExistsComparator
  hasDuplicateRelations: RelationExistsComparator
  hasErroredAgentSessions: RelationExistsComparator
  hasMergedAgentPullRequests: RelationExistsComparator
  hasRelatedRelations: RelationExistsComparator
  hasSharedUsers: RelationExistsComparator
  hasSuggestedAssignees: RelationExistsComparator
  hasSuggestedLabels: RelationExistsComparator
  hasSuggestedProjects: RelationExistsComparator
  hasSuggestedRelatedIssues: RelationExistsComparator
  hasSuggestedSimilarIssues: RelationExistsComparator
  hasSuggestedTeams: RelationExistsComparator
  id: IssueIDComparator
  labels: IssueLabelCollectionFilter
  lastAppliedTemplate: NullableTemplateFilter
  leadTime: NullableDurationComparator
  needs: CustomerNeedCollectionFilter
  null: Boolean
  number: NumberComparator
  or: [NullableIssueFilter!]
  parent: NullableIssueFilter
  priority: NullableNumberComparator
  project: NullableProjectFilter
  projectMilestone: NullableProjectMilestoneFilter
  reactions: ReactionCollectionFilter
  recurringIssueTemplate: NullableTemplateFilter
  releases: ReleaseCollectionFilter
  searchableContent: ContentComparator
  sharedWith: UserCollectionFilter
  slaBreachesAt: NullableDateComparator
  slaStatus: SlaStatusComparator
  snoozedBy: NullableUserFilter
  snoozedUntilAt: NullableDateComparator
  sourceMetadata: SourceMetadataComparator
  startedAt: NullableDateComparator
  state: WorkflowStateFilter
  subscribers: UserCollectionFilter
  suggestions: IssueSuggestionCollectionFilter
  team: TeamFilter
  title: StringComparator
  triageTime: NullableDurationComparator
  triagedAt: NullableDateComparator
  updatedAt: DateComparator
}

input NullableNumberComparator {
  eq: Float
  gt: Float
  gte: Float
  in: [Float!]
  lt: Float
  lte: Float
  neq: Float
  nin: [Float!]
  null: Boolean
}

input NullableProjectFilter {
  accessibleTeams: TeamCollectionFilter
  activityType: StringComparator
  and: [NullableProjectFilter!]
  canceledAt: NullableDateComparator
  completedAt: NullableDateComparator
  completedProjectMilestones: ProjectMilestoneCollectionFilter
  createdAt: DateComparator
  creator: UserFilter
  customIdentifier: NullableStringComparator
  customerCount: NumberComparator
  customerImportantCount: NumberComparator
  hasBlockedByRelations: RelationExistsComparator
  hasBlockingRelations: RelationExistsComparator
  hasDependedOnByRelations: RelationExistsComparator
  hasDependsOnRelations: RelationExistsComparator
  hasRelatedRelations: RelationExistsComparator
  hasViolatedRelations: RelationExistsComparator
  health: StringComparator
  healthWithAge: StringComparator
  id: EntityIdentifierIDComparator
  initiatives: InitiativeCollectionFilter
  issues: IssueCollectionFilter
  labels: ProjectLabelCollectionFilter
  lastAppliedTemplate: NullableTemplateFilter
  lead: NullableUserFilter
  leadTeam: NullableTeamFilter
  members: UserCollectionFilter
  name: StringComparator
  needs: CustomerNeedCollectionFilter
  nextProjectMilestone: ProjectMilestoneFilter
  null: Boolean
  or: [NullableProjectFilter!]
  priority: NullableNumberComparator
  projectMilestones: ProjectMilestoneCollectionFilter
  projectUpdates: ProjectUpdatesCollectionFilter
  roadmaps: RoadmapCollectionFilter
  searchableContent: ContentComparator
  slugId: StringComparator
  startDate: NullableDateComparator
  startedAt: NullableDateComparator
  state: StringComparator
  status: ProjectStatusFilter
  targetDate: NullableDateComparator
  updatedAt: DateComparator
}

input NullableProjectMilestoneFilter {
  and: [NullableProjectMilestoneFilter!]
  createdAt: DateComparator
  id: IDComparator
  name: NullableStringComparator
  null: Boolean
  or: [NullableProjectMilestoneFilter!]
  project: NullableProjectFilter
  targetDate: NullableDateComparator
  updatedAt: DateComparator
}

input NullableProjectUpdateFilter {
  and: [NullableProjectUpdateFilter!]
  createdAt: DateComparator
  id: IDComparator
  null: Boolean
  or: [NullableProjectUpdateFilter!]
  project: ProjectFilter
  reactions: ReactionCollectionFilter
  updatedAt: DateComparator
  user: UserFilter
}

input NullableStringComparator {
  contains: String
  containsIgnoreCase: String
  containsIgnoreCaseAndAccent: String
  endsWith: String
  eq: String
  eqIgnoreCase: String
  in: [String!]
  neq: String
  neqIgnoreCase: String
  nin: [String!]
  notContains: String
  notContainsIgnoreCase: String
  notEndsWith: String
  notStartsWith: String
  null: Boolean
  startsWith: String
  startsWithIgnoreCase: String
}

input NullableTeamFilter {
  ancestors: TeamCollectionFilter
  and: [NullableTeamFilter!]
  createdAt: DateComparator
  description: NullableStringComparator
  id: IDComparator
  issues: IssueCollectionFilter
  key: StringComparator
  members: UserCollectionFilter
  name: StringComparator
  null: Boolean
  or: [NullableTeamFilter!]
  owners: UserCollectionFilter
  parent: NullableTeamFilter
  private: BooleanComparator
  releasePipelines: ReleasePipelineCollectionFilter
  restrictedBy: NullableTeamFilter
  retiredAt: NullableDateComparator
  updatedAt: DateComparator
  users: UserCollectionFilter
  visibility: TeamVisibilityComparator
}

input NullableTemplateFilter {
  and: [NullableTemplateFilter!]
  createdAt: DateComparator
  id: IDComparator
  inheritedFromId: IDComparator
  name: StringComparator
  null: Boolean
  or: [NullableTemplateFilter!]
  team: NullableTeamFilter
  type: StringComparator
  updatedAt: DateComparator
}

input NullableTimelessDateComparator {
  eq: TimelessDateOrDuration
  gt: TimelessDateOrDuration
  gte: TimelessDateOrDuration
  in: [TimelessDateOrDuration!]
  lt: TimelessDateOrDuration
  lte: TimelessDateOrDuration
  neq: TimelessDateOrDuration
  nin: [TimelessDateOrDuration!]
  null: Boolean
}

input NullableUserFilter {
  active: BooleanComparator
  admin: BooleanComparator
  and: [NullableUserFilter!]
  app: BooleanComparator
  assignedIssues: IssueCollectionFilter
  createdAt: DateComparator
  displayName: StringComparator
  email: StringComparator
  id: IDComparator
  invited: BooleanComparator
  isInvited: BooleanComparator
  isMe: BooleanComparator
  name: StringComparator
  null: Boolean
  or: [NullableUserFilter!]
  owner: BooleanComparator
  updatedAt: DateComparator
}

input NumberComparator {
  eq: Float
  gt: Float
  gte: Float
  in: [Float!]
  lt: Float
  lte: Float
  neq: Float
  nin: [Float!]
}

type Organization implements Node {
  id: ID!
  name: String!
}

type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
}

enum PaginationNulls {
  first
  last
}

enum PaginationOrderBy {
  createdAt
  updatedAt
}

enum PaginationSortOrder {
  Ascending
  Descending
}

input PrioritySort {
  noPriorityFirst: Boolean = false
  nulls: PaginationNulls = last
  order: PaginationSortOrder
  usePrioritySortOrderTiebreaker: Boolean = true
}

type Project implements Node {
  attachments(after: String, before: String, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): ProjectAttachmentConnection!
  content: String
  createdAt: DateTime!
  description: String!
  documents(after: String, before: String, filter: DocumentFilter, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): DocumentConnection!
  externalLinks(after: String, before: String, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): EntityExternalLinkConnection!
  id: ID!
  identifier: String
  labels(after: String, before: String, filter: ProjectLabelFilter, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): ProjectLabelConnection!
  lastUpdate: ProjectUpdate
  lead: User
  members(after: String, before: String, filter: UserFilter, first: Int, includeArchived: Boolean, includeDisabled: Boolean, last: Int, orderBy: PaginationOrderBy): UserConnection!
  name: String!
  priority: Int!
  progress: Float!
  projectMilestones(after: String, before: String, filter: ProjectMilestoneFilter, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): ProjectMilestoneConnection!
  slugId: String!
  startDate: TimelessDate
  status: ProjectStatus!
  targetDate: TimelessDate
  teams(after: String, before: String, filter: TeamFilter, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): TeamConnection!
  updatedAt: DateTime!
  url: String!
}

type ProjectAttachment implements Node {
  id: ID!
  title: String!
  url: String!
}

type ProjectAttachmentConnection {
  nodes: [ProjectAttachment!]!
  pageInfo: PageInfo!
}

input ProjectCollectionFilter {
  accessibleTeams: TeamCollectionFilter
  activityType: StringComparator
  and: [ProjectCollectionFilter!]
  canceledAt: NullableDateComparator
  completedAt: NullableDateComparator
  completedProjectMilestones: ProjectMilestoneCollectionFilter
  createdAt: DateComparator
  creator: UserFilter
  customIdentifier: NullableStringComparator
  customerCount: NumberComparator
  customerImportantCount: NumberComparator
  every: ProjectFilter
  hasBlockedByRelations: RelationExistsComparator
  hasBlockingRelations: RelationExistsComparator
  hasDependedOnByRelations: RelationExistsComparator
  hasDependsOnRelations: RelationExistsComparator
  hasRelatedRelations: RelationExistsComparator
  hasViolatedRelations: RelationExistsComparator
  health: StringComparator
  healthWithAge: StringComparator
  id: EntityIdentifierIDComparator
  initiatives: InitiativeCollectionFilter
  issues: IssueCollectionFilter
  labels: ProjectLabelCollectionFilter
  lastAppliedTemplate: NullableTemplateFilter
  lead: NullableUserFilter
  leadTeam: NullableTeamFilter
  length: NumberComparator
  members: UserCollectionFilter
  name: StringComparator
  needs: CustomerNeedCollectionFilter
  nextProjectMilestone: ProjectMilestoneFilter
  or: [ProjectCollectionFilter!]
  priority: NullableNumberComparator
  projectMilestones: ProjectMilestoneCollectionFilter
  projectUpdates: ProjectUpdatesCollectionFilter
  roadmaps: RoadmapCollectionFilter
  searchableContent: ContentComparator
  slugId: StringComparator
  some: ProjectFilter
  startDate: NullableDateComparator
  startedAt: NullableDateComparator
  state: StringComparator
  status: ProjectStatusFilter
  targetDate: NullableDateComparator
  updatedAt: DateComparator
}

type ProjectConnection {
  nodes: [Project!]!
  pageInfo: PageInfo!
}

input ProjectCreateInput {
  color: String
  content: String
  convertedFromIssueId: String
  description: String
  icon: String
  id: String
  labelIds: [String!]
  lastAppliedTemplateId: String
  leadId: String
  leadTeamId: String
  memberIds: [String!]
  name: String!
  priority: Int
  prioritySortOrder: Float
  sortOrder: Float
  startDate: TimelessDate
  startDateResolution: DateResolutionType
  statusId: String
  targetDate: TimelessDate
  targetDateResolution: DateResolutionType
  teamIds: [String!]!
  templateId: String
  useDefaultTemplate: Boolean
}

input ProjectCreatedAtSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input ProjectFilter {
  accessibleTeams: TeamCollectionFilter
  activityType: StringComparator
  and: [ProjectFilter!]
  canceledAt: NullableDateComparator
  completedAt: NullableDateComparator
  completedProjectMilestones: ProjectMilestoneCollectionFilter
  createdAt: DateComparator
  creator: UserFilter
  customIdentifier: NullableStringComparator
  customerCount: NumberComparator
  customerImportantCount: NumberComparator
  hasBlockedByRelations: RelationExistsComparator
  hasBlockingRelations: RelationExistsComparator
  hasDependedOnByRelations: RelationExistsComparator
  hasDependsOnRelations: RelationExistsComparator
  hasRelatedRelations: RelationExistsComparator
  hasViolatedRelations: RelationExistsComparator
  health: StringComparator
  healthWithAge: StringComparator
  id: EntityIdentifierIDComparator
  initiatives: InitiativeCollectionFilter
  issues: IssueCollectionFilter
  labels: ProjectLabelCollectionFilter
  lastAppliedTemplate: NullableTemplateFilter
  lead: NullableUserFilter
  leadTeam: NullableTeamFilter
  members: UserCollectionFilter
  name: StringComparator
  needs: CustomerNeedCollectionFilter
  nextProjectMilestone: ProjectMilestoneFilter
  or: [ProjectFilter!]
  priority: NullableNumberComparator
  projectMilestones: ProjectMilestoneCollectionFilter
  projectUpdates: ProjectUpdatesCollectionFilter
  roadmaps: RoadmapCollectionFilter
  searchableContent: ContentComparator
  slugId: StringComparator
  startDate: NullableDateComparator
  startedAt: NullableDateComparator
  state: StringComparator
  status: ProjectStatusFilter
  targetDate: NullableDateComparator
  updatedAt: DateComparator
}

input ProjectHealthSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

type ProjectLabel implements Node {
  id: ID!
  name: String!
}

input ProjectLabelCollectionFilter {
  and: [ProjectLabelCollectionFilter!]
  createdAt: DateComparator
  creator: NullableUserFilter
  every: ProjectLabelFilter
  id: IDComparator
  isGroup: BooleanComparator
  length: NumberComparator
  name: StringComparator
  null: Boolean
  or: [ProjectLabelCollectionFilter!]
  parent: ProjectLabelFilter
  some: ProjectLabelCollectionFilter
  team: NullableTeamFilter
  updatedAt: DateComparator
}

type ProjectLabelConnection {
  nodes: [ProjectLabel!]!
}

input ProjectLabelFilter {
  and: [ProjectLabelFilter!]
  createdAt: DateComparator
  creator: NullableUserFilter
  id: IDComparator
  isGroup: BooleanComparator
  name: StringComparator
  or: [ProjectLabelFilter!]
  parent: ProjectLabelFilter
  team: NullableTeamFilter
  updatedAt: DateComparator
}

input ProjectLeadSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input ProjectManualSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

type ProjectMilestone implements Node {
  description: String
  id: ID!
  name: String!
  project: Project!
  targetDate: TimelessDate
}

input ProjectMilestoneCollectionFilter {
  and: [ProjectMilestoneCollectionFilter!]
  createdAt: DateComparator
  every: ProjectMilestoneFilter
  id: IDComparator
  length: NumberComparator
  name: NullableStringComparator
  or: [ProjectMilestoneCollectionFilter!]
  project: NullableProjectFilter
  some: ProjectMilestoneFilter
  targetDate: NullableDateComparator
  updatedAt: DateComparator
}

type ProjectMilestoneConnection {
  nodes: [ProjectMilestone!]!
  pageInfo: PageInfo!
}

input ProjectMilestoneFilter {
  and: [ProjectMilestoneFilter!]
  createdAt: DateComparator
  id: IDComparator
  name: NullableStringComparator
  or: [ProjectMilestoneFilter!]
  project: NullableProjectFilter
  targetDate: NullableDateComparator
  updatedAt: DateComparator
}

input ProjectNameSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

type ProjectPayload {
  project: Project
  success: Boolean!
}

input ProjectPrioritySort {
  noPriorityFirst: Boolean = false
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input ProjectSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input ProjectSortInput {
  createdAt: ProjectCreatedAtSort
  health: ProjectHealthSort
  lead: ProjectLeadSort
  manual: ProjectManualSort
  name: ProjectNameSort
  priority: ProjectPrioritySort
  startDate: StartDateSort
  status: ProjectStatusSort
  targetDate: TargetDateSort
  updatedAt: ProjectUpdatedAtSort
}

type ProjectStatus implements Node {
  id: ID!
  name: String!
  type: ProjectStatusType!
}

type ProjectStatusConnection {
  nodes: [ProjectStatus!]!
  pageInfo: PageInfo!
}

input ProjectStatusFilter {
  and: [ProjectStatusFilter!]
  createdAt: DateComparator
  description: StringComparator
  id: IDComparator
  name: StringComparator
  or: [ProjectStatusFilter!]
  position: NumberComparator
  projects: ProjectCollectionFilter
  team: NullableTeamFilter
  type: StringComparator
  updatedAt: DateComparator
}

input ProjectStatusSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

enum ProjectStatusType {
  backlog
  canceled
  completed
  paused
  planned
  started
}

type ProjectUpdate implements Node {
  body: String!
  createdAt: DateTime!
  health: ProjectUpdateHealthType!
  id: ID!
  isDiffHidden: Boolean!
  project: Project!
  updatedAt: DateTime!
  url: String!
  user: User!
}

type ProjectUpdateConnection {
  nodes: [ProjectUpdate!]!
  pageInfo: PageInfo!
}

input ProjectUpdateCreateInput {
  body: String
  bodyData: JSON
  health: ProjectUpdateHealthType
  id: String
  isDiffHidden: Boolean
  projectId: String!
}

input ProjectUpdateFilter {
  and: [ProjectUpdateFilter!]
  createdAt: DateComparator
  id: IDComparator
  or: [ProjectUpdateFilter!]
  project: ProjectFilter
  reactions: ReactionCollectionFilter
  updatedAt: DateComparator
  user: UserFilter
}

enum ProjectUpdateHealthType {
  atRisk
  offTrack
  onTrack
}

input ProjectUpdateInput {
  canceledAt: DateTime
  color: String
  completedAt: DateTime
  content: String
  convertedFromIssueId: String
  description: String
  frequencyResolution: FrequencyResolutionType
  icon: String
  labelIds: [String!]
  lastAppliedTemplateId: String
  leadId: String
  leadTeamId: String
  memberIds: [String!]
  name: String
  priority: Int
  prioritySortOrder: Float
  projectUpdateRemindersPausedUntilAt: DateTime
  slackIssueComments: Boolean
  slackIssueStatuses: Boolean
  slackNewIssue: Boolean
  sortOrder: Float
  startDate: TimelessDate
  startDateResolution: DateResolutionType
  statusId: String
  targetDate: TimelessDate
  targetDateResolution: DateResolutionType
  teamIds: [String!]
  trashed: Boolean
  updateReminderFrequency: Float
  updateReminderFrequencyInWeeks: Float
  updateRemindersDay: Day
  updateRemindersHour: Int
}

type ProjectUpdatePayload {
  projectUpdate: ProjectUpdate!
  success: Boolean!
}

input ProjectUpdateUpdateInput {
  body: String
  bodyData: JSON
  health: ProjectUpdateHealthType
}

input ProjectUpdatedAtSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input ProjectUpdatesCollectionFilter {
  and: [ProjectUpdatesCollectionFilter!]
  createdAt: DateComparator
  every: ProjectUpdatesFilter
  health: StringComparator
  id: IDComparator
  length: NumberComparator
  or: [ProjectUpdatesCollectionFilter!]
  some: ProjectUpdatesFilter
  updatedAt: DateComparator
}

input ProjectUpdatesFilter {
  and: [ProjectUpdatesFilter!]
  createdAt: DateComparator
  health: StringComparator
  id: IDComparator
  or: [ProjectUpdatesFilter!]
  updatedAt: DateComparator
}

type Query {
  comment(hash: String, id: String): Comment!
  comments(after: String, before: String, filter: CommentFilter, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): CommentConnection!
  document(id: String!): Document!
  initiative(id: String!): Initiative!
  initiatives(after: String, before: String, filter: InitiativeFilter, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy, sort: [InitiativeSortInput!]): InitiativeConnection!
  issue(id: String!): Issue!
  issueLabels(after: String, before: String, filter: IssueLabelFilter, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): IssueLabelConnection!
  issueRelations(after: String, before: String, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): IssueRelationConnection!
  issues(after: String, before: String, filter: IssueFilter, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy, sort: [IssueSortInput!]): IssueConnection!
  organization: Organization!
  project(id: String!): Project!
  projectMilestones(after: String, before: String, filter: ProjectMilestoneFilter, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): ProjectMilestoneConnection!
  projectStatuses(after: String, before: String, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): ProjectStatusConnection!
  projectUpdate(id: String!, projectId: String): ProjectUpdate!
  projectUpdates(after: String, before: String, filter: ProjectUpdateFilter, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): ProjectUpdateConnection!
  projects(after: String, before: String, filter: ProjectFilter, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy, sort: [ProjectSortInput!]): ProjectConnection!
  searchIssues(after: String, before: String, filter: IssueFilter, first: Int, includeArchived: Boolean, includeComments: Boolean, last: Int, orderBy: PaginationOrderBy, teamId: String, term: String!): IssueSearchPayload!
  teams(after: String, before: String, filter: TeamFilter, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): TeamConnection!
  users(after: String, before: String, filter: UserFilter, first: Int, includeArchived: Boolean, includeDisabled: Boolean, last: Int, orderBy: PaginationOrderBy, sort: [UserSortInput!]): UserConnection!
  viewer: User!
  workflowStates(after: String, before: String, filter: WorkflowStateFilter, first: Int, includeArchived: Boolean, last: Int, orderBy: PaginationOrderBy): WorkflowStateConnection!
}

input ReactionCollectionFilter {
  and: [ReactionCollectionFilter!]
  createdAt: DateComparator
  customEmojiId: IDComparator
  emoji: StringComparator
  every: ReactionFilter
  id: IDComparator
  length: NumberComparator
  or: [ReactionCollectionFilter!]
  some: ReactionFilter
  updatedAt: DateComparator
}

input ReactionFilter {
  and: [ReactionFilter!]
  createdAt: DateComparator
  customEmojiId: IDComparator
  emoji: StringComparator
  id: IDComparator
  or: [ReactionFilter!]
  updatedAt: DateComparator
}

input RelationExistsComparator {
  eq: Boolean
  neq: Boolean
}

input ReleaseCollectionFilter {
  and: [ReleaseCollectionFilter!]
  completedAt: NullableDateComparator
  createdAt: DateComparator
  every: ReleaseFilter
  hasReleaseNotes: BooleanComparator
  id: IDComparator
  length: NumberComparator
  name: StringComparator
  or: [ReleaseCollectionFilter!]
  pipeline: ReleasePipelineFilter
  some: ReleaseFilter
  stage: ReleaseStageFilter
  updatedAt: DateComparator
  version: StringComparator
}

input ReleaseFilter {
  and: [ReleaseFilter!]
  completedAt: NullableDateComparator
  createdAt: DateComparator
  hasReleaseNotes: BooleanComparator
  id: IDComparator
  name: StringComparator
  or: [ReleaseFilter!]
  pipeline: ReleasePipelineFilter
  stage: ReleaseStageFilter
  updatedAt: DateComparator
  version: StringComparator
}

input ReleasePipelineCollectionFilter {
  and: [ReleasePipelineCollectionFilter!]
  createdAt: DateComparator
  every: ReleasePipelineFilter
  id: IDComparator
  isProduction: BooleanComparator
  length: NumberComparator
  name: StringComparator
  or: [ReleasePipelineCollectionFilter!]
  some: ReleasePipelineFilter
  teams: TeamCollectionFilter
  type: ReleasePipelineTypeComparator
  updatedAt: DateComparator
}

input ReleasePipelineFilter {
  and: [ReleasePipelineFilter!]
  createdAt: DateComparator
  id: IDComparator
  isProduction: BooleanComparator
  name: StringComparator
  or: [ReleasePipelineFilter!]
  teams: TeamCollectionFilter
  type: ReleasePipelineTypeComparator
  updatedAt: DateComparator
}

enum ReleasePipelineType {
  continuous
  scheduled
}

input ReleasePipelineTypeComparator {
  eq: ReleasePipelineType
  in: [ReleasePipelineType!]
  neq: ReleasePipelineType
  nin: [ReleasePipelineType!]
  null: Boolean
}

input ReleaseSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input ReleaseStageFilter {
  and: [ReleaseStageFilter!]
  createdAt: DateComparator
  id: IDComparator
  name: StringComparator
  or: [ReleaseStageFilter!]
  type: ReleaseStageTypeComparator
  updatedAt: DateComparator
}

enum ReleaseStageType {
  canceled
  completed
  planned
  started
}

input ReleaseStageTypeComparator {
  eq: ReleaseStageType
  in: [ReleaseStageType!]
  neq: ReleaseStageType
  nin: [ReleaseStageType!]
  null: Boolean
}

input RoadmapCollectionFilter {
  and: [RoadmapCollectionFilter!]
  createdAt: DateComparator
  creator: UserFilter
  every: RoadmapFilter
  id: IDComparator
  length: NumberComparator
  name: StringComparator
  or: [RoadmapCollectionFilter!]
  slugId: StringComparator
  some: RoadmapFilter
  updatedAt: DateComparator
}

input RoadmapFilter {
  and: [RoadmapFilter!]
  createdAt: DateComparator
  creator: UserFilter
  id: IDComparator
  name: StringComparator
  or: [RoadmapFilter!]
  slugId: StringComparator
  updatedAt: DateComparator
}

input RootIssueSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
  sort: IssueSortInput!
}

enum SLADayCountType {
  all
  onlyBusinessDays
}

input SalesforceMetadataIntegrationComparator {
  caseMetadata: JSONObject
}

enum SlaStatus {
  Breached
  Completed
  Failed
  HighRisk
  LowRisk
  MediumRisk
}

input SlaStatusComparator {
  eq: SlaStatus
  in: [SlaStatus!]
  neq: SlaStatus
  nin: [SlaStatus!]
  null: Boolean
}

input SlaStatusSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input SourceMetadataComparator {
  null: Boolean
  salesforceMetadata: SalesforceMetadataIntegrationComparator
  subType: SubTypeComparator
  workflowDefinitionId: WorkflowDefinitionIdComparator
}

input SourceTypeComparator {
  contains: String
  containsIgnoreCase: String
  containsIgnoreCaseAndAccent: String
  endsWith: String
  eq: String
  eqIgnoreCase: String
  in: [String!]
  neq: String
  neqIgnoreCase: String
  nin: [String!]
  notContains: String
  notContainsIgnoreCase: String
  notEndsWith: String
  notStartsWith: String
  startsWith: String
  startsWithIgnoreCase: String
}

input StartDateSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input StringArrayComparator {
  every: StringItemComparator
  length: NumberComparator
  some: StringItemComparator
}

input StringComparator {
  contains: String
  containsIgnoreCase: String
  containsIgnoreCaseAndAccent: String
  endsWith: String
  eq: String
  eqIgnoreCase: String
  in: [String!]
  neq: String
  neqIgnoreCase: String
  nin: [String!]
  notContains: String
  notContainsIgnoreCase: String
  notEndsWith: String
  notStartsWith: String
  startsWith: String
  startsWithIgnoreCase: String
}

input StringItemComparator {
  contains: String
  containsIgnoreCase: String
  containsIgnoreCaseAndAccent: String
  endsWith: String
  eq: String
  eqIgnoreCase: String
  in: [String!]
  neq: String
  neqIgnoreCase: String
  nin: [String!]
  notContains: String
  notContainsIgnoreCase: String
  notEndsWith: String
  notStartsWith: String
  startsWith: String
  startsWithIgnoreCase: String
}

input SubTypeComparator {
  eq: String
  in: [String!]
  neq: String
  nin: [String!]
  null: Boolean
}

input TargetDateSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

type Team implements Node {
  id: ID!
  key: String!
  name: String!
}

input TeamCollectionFilter {
  ancestors: TeamCollectionFilter
  and: [TeamCollectionFilter!]
  createdAt: DateComparator
  every: TeamFilter
  id: IDComparator
  length: NumberComparator
  or: [TeamCollectionFilter!]
  parent: NullableTeamFilter
  some: TeamFilter
  updatedAt: DateComparator
}

type TeamConnection {
  nodes: [Team!]!
  pageInfo: PageInfo!
}

input TeamFilter {
  ancestors: TeamCollectionFilter
  and: [TeamFilter!]
  createdAt: DateComparator
  description: NullableStringComparator
  id: IDComparator
  issues: IssueCollectionFilter
  key: StringComparator
  members: UserCollectionFilter
  name: StringComparator
  or: [TeamFilter!]
  owners: UserCollectionFilter
  parent: NullableTeamFilter
  private: BooleanComparator
  releasePipelines: ReleasePipelineCollectionFilter
  restrictedBy: NullableTeamFilter
  retiredAt: NullableDateComparator
  updatedAt: DateComparator
  users: UserCollectionFilter
  visibility: TeamVisibilityComparator
}

input TeamSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

enum TeamVisibility {
  private
  public
  restricted
}

input TeamVisibilityComparator {
  eq: TeamVisibility
  in: [TeamVisibility!]
  neq: TeamVisibility
  nin: [TeamVisibility!]
}

input TimeInStatusSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

scalar TimelessDate

scalar TimelessDateOrDuration

input TitleSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input UpdatedAtSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

type User implements Node {
  app: Boolean!
  displayName: String!
  email: String!
  id: ID!
  name: String!
}

input UserCollectionFilter {
  active: BooleanComparator
  admin: BooleanComparator
  and: [UserCollectionFilter!]
  app: BooleanComparator
  assignedIssues: IssueCollectionFilter
  createdAt: DateComparator
  displayName: StringComparator
  email: StringComparator
  every: UserFilter
  id: IDComparator
  invited: BooleanComparator
  isInvited: BooleanComparator
  isMe: BooleanComparator
  length: NumberComparator
  name: StringComparator
  or: [UserCollectionFilter!]
  owner: BooleanComparator
  some: UserFilter
  updatedAt: DateComparator
}

type UserConnection {
  nodes: [User!]!
  pageInfo: PageInfo!
}

input UserDisplayNameSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input UserFilter {
  active: BooleanComparator
  admin: BooleanComparator
  and: [UserFilter!]
  app: BooleanComparator
  assignedIssues: IssueCollectionFilter
  createdAt: DateComparator
  displayName: StringComparator
  email: StringComparator
  id: IDComparator
  invited: BooleanComparator
  isInvited: BooleanComparator
  isMe: BooleanComparator
  name: StringComparator
  or: [UserFilter!]
  owner: BooleanComparator
  updatedAt: DateComparator
}

input UserNameSort {
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}

input UserSortInput {
  displayName: UserDisplayNameSort
  name: UserNameSort
}

input WorkflowDefinitionIdComparator {
  eq: ID
  in: [ID!]
  neq: ID
  nin: [ID!]
  null: Boolean
}

type WorkflowState implements Node {
  id: ID!
  name: String!
  team: Team!
  type: String!
}

type WorkflowStateConnection {
  nodes: [WorkflowState!]!
  pageInfo: PageInfo!
}

input WorkflowStateFilter {
  and: [WorkflowStateFilter!]
  createdAt: DateComparator
  description: StringComparator
  id: IDComparator
  issues: IssueCollectionFilter
  name: StringComparator
  or: [WorkflowStateFilter!]
  position: NumberComparator
  team: TeamFilter
  type: StringComparator
  updatedAt: DateComparator
}

input WorkflowStateSort {
  closedIssuesOrderedByRecency: Boolean = false
  nulls: PaginationNulls = last
  order: PaginationSortOrder
}
