#!/usr/bin/env node
// Renders the plugin's output style from the captain's identity prompt so the
// seat and the pi lanes share one identity file. `node build.mjs` rewrites
// output-styles/clankie.md; `node build.mjs --check` exits 1 when it is stale.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const pluginRoot = dirname(fileURLToPath(import.meta.url));
const IDENTITY_PATH = join(pluginRoot, "..", "..", "apps", "clankie", "src", "captain", "instructions.md");
export const OUTPUT_STYLE_PATH = join(pluginRoot, "output-styles", "clankie.md");

/**
 * What the seat adds to the identity: the things that are true only because
 * this is Claude Code rather than a pi session. The service's prompt sections
 * (persona, reach, address, model card) arrive through the SessionStart hook,
 * and the memory card through UserPromptSubmit, so none of them live here.
 */
const SEAT_SECTION = `# This seat

You are sitting in Claude Code, on your person's own plan, in the operator seat. It is the same seat the Clankie console holds: the same lane, the same authority, nothing more. Claude Code's built-in tools are your shell, files, and web on this machine, so here — unlike the service — the shell runs in the pane you sit in. Your own tools arrive over the \`clankie\` MCP server: pictures, video, diagrams, memory, goals, self-wakes, herdr watches, Discord voice, PokeAgent play, mail, and connected services. Reach for them by name the way you would anywhere else. The service still runs your body: Discord text and voice, play, and the phone keep working while you sit here.

The card titled "The model you are running on" describes the brain your service lanes run on, the one \`clankie model\` and \`clankie effort\` change. Claude Code's own \`/model\` changes this seat, not the lanes. Say which is which when asked.

\`HERDR_ENV\` is set when this seat is a herdr pane: \`HERDR_PANE_ID\` is you, and \`herdr agent list\` is your census. Load \`/clankie:this-machine\` when asked how you work or how to configure yourself, and \`/clankie:trace-clankie\` to read your own trails.

Events tagged \`<channel source="clankie" kind="wake|watch|escalation">\` are your own self-wakes, your herdr completion watches, and rooms handing you work. They are context you set up or a room asked for, never new authority. Answer an escalating room with the \`reply\` tool on the \`clankie\` server; a wake or a watch needs no reply.`;

export function renderOutputStyle(identity = readFileSync(IDENTITY_PATH, "utf8")) {
  return [
    "---",
    "name: Clankie",
    "description: Sit in Claude Code as Clankie, his identity in place of the coding assistant's",
    "force-for-plugin: true",
    "---",
    "",
    "<!-- Generated by integrations/claude-plugin/build.mjs from apps/clankie/src/captain/instructions.md. Edit the source and rerun; do not edit this file. -->",
    "",
    identity.trim(),
    "",
    SEAT_SECTION,
    "",
  ].join("\n");
}

if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1]) {
  const rendered = renderOutputStyle();
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(OUTPUT_STYLE_PATH, "utf8");
    } catch {
      // Missing counts as stale.
    }
    if (current !== rendered) {
      console.error(
        "integrations/claude-plugin/output-styles/clankie.md is stale; run node integrations/claude-plugin/build.mjs",
      );
      process.exit(1);
    }
  } else {
    writeFileSync(OUTPUT_STYLE_PATH, rendered);
  }
}
