// GENERATED by scripts/garden-sprites/generate.mjs — do not edit
// Source grids: scripts/garden-sprites/{frames,lifecycle}.mjs · palette: scripts/garden-sprites/palette.mjs
// Atlas image: assets/garden-atlas/leafguy-atlas.png

export const ATLAS_SIZE = { width: 255, height: 391 } as const;

// prettier-ignore
export type GardenFrameName =
  | 'idle0' | 'idle1' | 'walk0' | 'walk1' | 'walk2'
  | 'walk3' | 'work0' | 'work1' | 'carry0' | 'carry1'
  | 'blocked0' | 'sleep0' | 'sleep1' | 'poof0' | 'poof1'
  | 'poof2' | 'stump' | 'jobsite' | 'leaf' | 'wateringCan'
  | 'signpost' | 'glyphQ' | 'glyphZ' | 'glyphBang' | 'glyphDots'
  | 'wilt0' | 'wilt1' | 'seed0' | 'seed1' | 'germinate0'
  | 'germinate1' | 'germinate2' | 'seedSink0' | 'seedSink1' | 'meadowTuft'
  | 'meadowTuftTall' | 'meadowClover' | 'meadowDaisy' | 'meadowPebbles' | 'tideStone'
  | 'tideStoneSm' | 'tideLily' | 'tideReed' | 'tideRipple' | 'tidePool'
  | 'fernFrond' | 'fernPair' | 'fernMoss' | 'fernShoot' | 'fernClump'
  | 'sunflowerHead' | 'sunflowerBud' | 'sunflowerStalk' | 'sunflowerSprout' | 'sunflowerTall'
  | 'mushroomCap' | 'mushroomPair' | 'mushroomTiny' | 'mushroomSpores' | 'mushroomCluster'
  | 'rockStone' | 'rockStoneSm' | 'rockRaked' | 'rockCairn' | 'rockBoulder'
  | 'compostLeaf' | 'compostLitter' | 'compostTwig' | 'compostMound' | 'compostHeap'
  | 'pathWorn' | 'totem' | 'skillStar' | 'skillBolt' | 'skillEye'
  | 'skillArrow' | 'skillDrop' | 'skillLeaf' | 'skillRing' | 'leadCrown';

export interface AtlasFrame {
  x: number;
  y: number;
  w: number;
  h: number;
}

// prettier-ignore
export const ATLAS_FRAMES: Record<GardenFrameName, AtlasFrame> = {
  idle0: { x: 50, y: 1, w: 24, h: 28 },
  idle1: { x: 75, y: 1, w: 24, h: 28 },
  walk0: { x: 100, y: 1, w: 24, h: 28 },
  walk1: { x: 125, y: 1, w: 24, h: 28 },
  walk2: { x: 150, y: 1, w: 24, h: 28 },
  walk3: { x: 175, y: 1, w: 24, h: 28 },
  work0: { x: 200, y: 1, w: 24, h: 28 },
  work1: { x: 225, y: 1, w: 24, h: 28 },
  carry0: { x: 1, y: 42, w: 24, h: 28 },
  carry1: { x: 26, y: 42, w: 24, h: 28 },
  blocked0: { x: 51, y: 42, w: 24, h: 28 },
  sleep0: { x: 76, y: 42, w: 24, h: 28 },
  sleep1: { x: 101, y: 42, w: 24, h: 28 },
  poof0: { x: 126, y: 42, w: 24, h: 28 },
  poof1: { x: 151, y: 42, w: 24, h: 28 },
  poof2: { x: 176, y: 42, w: 24, h: 28 },
  stump: { x: 1, y: 1, w: 48, h: 40 },
  jobsite: { x: 193, y: 332, w: 32, h: 16 },
  leaf: { x: 167, y: 361, w: 12, h: 10 },
  wateringCan: { x: 58, y: 361, w: 16, h: 12 },
  signpost: { x: 151, y: 332, w: 22, h: 26 },
  glyphQ: { x: 223, y: 361, w: 8, h: 10 },
  glyphZ: { x: 232, y: 361, w: 8, h: 10 },
  glyphBang: { x: 241, y: 361, w: 8, h: 10 },
  glyphDots: { x: 1, y: 374, w: 8, h: 10 },
  wilt0: { x: 201, y: 42, w: 24, h: 28 },
  wilt1: { x: 226, y: 42, w: 24, h: 28 },
  seed0: { x: 75, y: 361, w: 12, h: 12 },
  seed1: { x: 88, y: 361, w: 12, h: 12 },
  germinate0: { x: 1, y: 71, w: 24, h: 28 },
  germinate1: { x: 26, y: 71, w: 24, h: 28 },
  germinate2: { x: 51, y: 71, w: 24, h: 28 },
  seedSink0: { x: 101, y: 361, w: 12, h: 12 },
  seedSink1: { x: 114, y: 361, w: 12, h: 12 },
  meadowTuft: { x: 134, y: 374, w: 9, h: 7 },
  meadowTuftTall: { x: 193, y: 361, w: 9, h: 10 },
  meadowClover: { x: 205, y: 374, w: 7, h: 6 },
  meadowDaisy: { x: 220, y: 374, w: 5, h: 6 },
  meadowPebbles: { x: 34, y: 385, w: 8, h: 5 },
  tideStone: { x: 196, y: 374, w: 8, h: 6 },
  tideStoneSm: { x: 43, y: 385, w: 6, h: 5 },
  tideLily: { x: 44, y: 374, w: 11, h: 8 },
  tideReed: { x: 10, y: 374, w: 6, h: 10 },
  tideRipple: { x: 13, y: 385, w: 10, h: 5 },
  tidePool: { x: 1, y: 361, w: 18, h: 12 },
  fernFrond: { x: 203, y: 361, w: 9, h: 10 },
  fernPair: { x: 180, y: 361, w: 12, h: 10 },
  fernMoss: { x: 24, y: 385, w: 9, h: 5 },
  fernShoot: { x: 127, y: 374, w: 6, h: 8 },
  fernClump: { x: 152, y: 361, w: 14, h: 10 },
  sunflowerHead: { x: 213, y: 361, w: 9, h: 10 },
  sunflowerBud: { x: 37, y: 374, w: 6, h: 9 },
  sunflowerStalk: { x: 144, y: 361, w: 7, h: 11 },
  sunflowerSprout: { x: 213, y: 374, w: 6, h: 6 },
  sunflowerTall: { x: 226, y: 332, w: 18, h: 13 },
  mushroomCap: { x: 119, y: 374, w: 7, h: 8 },
  mushroomPair: { x: 17, y: 374, w: 11, h: 9 },
  mushroomTiny: { x: 64, y: 385, w: 5, h: 5 },
  mushroomSpores: { x: 186, y: 374, w: 9, h: 6 },
  mushroomCluster: { x: 20, y: 361, w: 18, h: 12 },
  rockStone: { x: 144, y: 374, w: 9, h: 7 },
  rockStoneSm: { x: 50, y: 385, w: 6, h: 5 },
  rockRaked: { x: 226, y: 374, w: 14, h: 5 },
  rockCairn: { x: 29, y: 374, w: 7, h: 9 },
  rockBoulder: { x: 127, y: 361, w: 16, h: 11 },
  compostLeaf: { x: 57, y: 385, w: 6, h: 5 },
  compostLitter: { x: 241, y: 374, w: 12, h: 5 },
  compostTwig: { x: 70, y: 385, w: 9, h: 4 },
  compostMound: { x: 175, y: 374, w: 10, h: 6 },
  compostHeap: { x: 39, y: 361, w: 18, h: 12 },
  pathWorn: { x: 154, y: 374, w: 20, h: 6 },
  totem: { x: 174, y: 332, w: 18, h: 26 },
  skillStar: { x: 56, y: 374, w: 8, h: 8 },
  skillBolt: { x: 65, y: 374, w: 8, h: 8 },
  skillEye: { x: 74, y: 374, w: 8, h: 8 },
  skillArrow: { x: 83, y: 374, w: 8, h: 8 },
  skillDrop: { x: 92, y: 374, w: 8, h: 8 },
  skillLeaf: { x: 101, y: 374, w: 8, h: 8 },
  skillRing: { x: 110, y: 374, w: 8, h: 8 },
  leadCrown: { x: 1, y: 385, w: 11, h: 5 },
};

// --- Harness variants (VUH-454) --------------------------------------------
// A worker's harness maps to a leaf tint; body Atlas rects come from
// VARIANT_BODY_FRAMES[worker.variant]. 'green' aliases the base ATLAS_FRAMES, so
// existing consumers keep working. Accessories ride a separate upright overlay
// slot (green has none).
// prettier-ignore
export type GardenVariant = 'green' | 'teal' | 'amber' | 'dusk' | 'onyx' | 'azure' | 'gold';

// prettier-ignore
export type GardenBodyFrameName =
  | 'idle0' | 'idle1' | 'walk0' | 'walk1' | 'walk2'
  | 'walk3' | 'work0' | 'work1' | 'carry0' | 'carry1'
  | 'blocked0' | 'sleep0' | 'sleep1' | 'wilt0' | 'wilt1'
  | 'poof0' | 'poof1' | 'poof2';

// prettier-ignore
export const VARIANT_BODY_FRAMES: Record<GardenVariant, Record<GardenBodyFrameName, AtlasFrame>> = {
  green: {
    idle0: { x: 50, y: 1, w: 24, h: 28 },
    idle1: { x: 75, y: 1, w: 24, h: 28 },
    walk0: { x: 100, y: 1, w: 24, h: 28 },
    walk1: { x: 125, y: 1, w: 24, h: 28 },
    walk2: { x: 150, y: 1, w: 24, h: 28 },
    walk3: { x: 175, y: 1, w: 24, h: 28 },
    work0: { x: 200, y: 1, w: 24, h: 28 },
    work1: { x: 225, y: 1, w: 24, h: 28 },
    carry0: { x: 1, y: 42, w: 24, h: 28 },
    carry1: { x: 26, y: 42, w: 24, h: 28 },
    blocked0: { x: 51, y: 42, w: 24, h: 28 },
    sleep0: { x: 76, y: 42, w: 24, h: 28 },
    sleep1: { x: 101, y: 42, w: 24, h: 28 },
    wilt0: { x: 201, y: 42, w: 24, h: 28 },
    wilt1: { x: 226, y: 42, w: 24, h: 28 },
    poof0: { x: 126, y: 42, w: 24, h: 28 },
    poof1: { x: 151, y: 42, w: 24, h: 28 },
    poof2: { x: 176, y: 42, w: 24, h: 28 },
  },
  teal: {
    idle0: { x: 76, y: 71, w: 24, h: 28 },
    idle1: { x: 101, y: 71, w: 24, h: 28 },
    walk0: { x: 126, y: 71, w: 24, h: 28 },
    walk1: { x: 151, y: 71, w: 24, h: 28 },
    walk2: { x: 176, y: 71, w: 24, h: 28 },
    walk3: { x: 201, y: 71, w: 24, h: 28 },
    work0: { x: 226, y: 71, w: 24, h: 28 },
    work1: { x: 1, y: 100, w: 24, h: 28 },
    carry0: { x: 26, y: 100, w: 24, h: 28 },
    carry1: { x: 51, y: 100, w: 24, h: 28 },
    blocked0: { x: 76, y: 100, w: 24, h: 28 },
    sleep0: { x: 101, y: 100, w: 24, h: 28 },
    sleep1: { x: 126, y: 100, w: 24, h: 28 },
    wilt0: { x: 151, y: 100, w: 24, h: 28 },
    wilt1: { x: 176, y: 100, w: 24, h: 28 },
    poof0: { x: 126, y: 42, w: 24, h: 28 },
    poof1: { x: 151, y: 42, w: 24, h: 28 },
    poof2: { x: 176, y: 42, w: 24, h: 28 },
  },
  amber: {
    idle0: { x: 201, y: 100, w: 24, h: 28 },
    idle1: { x: 226, y: 100, w: 24, h: 28 },
    walk0: { x: 1, y: 129, w: 24, h: 28 },
    walk1: { x: 26, y: 129, w: 24, h: 28 },
    walk2: { x: 51, y: 129, w: 24, h: 28 },
    walk3: { x: 76, y: 129, w: 24, h: 28 },
    work0: { x: 101, y: 129, w: 24, h: 28 },
    work1: { x: 126, y: 129, w: 24, h: 28 },
    carry0: { x: 151, y: 129, w: 24, h: 28 },
    carry1: { x: 176, y: 129, w: 24, h: 28 },
    blocked0: { x: 201, y: 129, w: 24, h: 28 },
    sleep0: { x: 226, y: 129, w: 24, h: 28 },
    sleep1: { x: 1, y: 158, w: 24, h: 28 },
    wilt0: { x: 26, y: 158, w: 24, h: 28 },
    wilt1: { x: 51, y: 158, w: 24, h: 28 },
    poof0: { x: 126, y: 42, w: 24, h: 28 },
    poof1: { x: 151, y: 42, w: 24, h: 28 },
    poof2: { x: 176, y: 42, w: 24, h: 28 },
  },
  dusk: {
    idle0: { x: 76, y: 158, w: 24, h: 28 },
    idle1: { x: 101, y: 158, w: 24, h: 28 },
    walk0: { x: 126, y: 158, w: 24, h: 28 },
    walk1: { x: 151, y: 158, w: 24, h: 28 },
    walk2: { x: 176, y: 158, w: 24, h: 28 },
    walk3: { x: 201, y: 158, w: 24, h: 28 },
    work0: { x: 226, y: 158, w: 24, h: 28 },
    work1: { x: 1, y: 187, w: 24, h: 28 },
    carry0: { x: 26, y: 187, w: 24, h: 28 },
    carry1: { x: 51, y: 187, w: 24, h: 28 },
    blocked0: { x: 76, y: 187, w: 24, h: 28 },
    sleep0: { x: 101, y: 187, w: 24, h: 28 },
    sleep1: { x: 126, y: 187, w: 24, h: 28 },
    wilt0: { x: 151, y: 187, w: 24, h: 28 },
    wilt1: { x: 176, y: 187, w: 24, h: 28 },
    poof0: { x: 126, y: 42, w: 24, h: 28 },
    poof1: { x: 151, y: 42, w: 24, h: 28 },
    poof2: { x: 176, y: 42, w: 24, h: 28 },
  },
  onyx: {
    idle0: { x: 201, y: 187, w: 24, h: 28 },
    idle1: { x: 226, y: 187, w: 24, h: 28 },
    walk0: { x: 1, y: 216, w: 24, h: 28 },
    walk1: { x: 26, y: 216, w: 24, h: 28 },
    walk2: { x: 51, y: 216, w: 24, h: 28 },
    walk3: { x: 76, y: 216, w: 24, h: 28 },
    work0: { x: 101, y: 216, w: 24, h: 28 },
    work1: { x: 126, y: 216, w: 24, h: 28 },
    carry0: { x: 151, y: 216, w: 24, h: 28 },
    carry1: { x: 176, y: 216, w: 24, h: 28 },
    blocked0: { x: 201, y: 216, w: 24, h: 28 },
    sleep0: { x: 226, y: 216, w: 24, h: 28 },
    sleep1: { x: 1, y: 245, w: 24, h: 28 },
    wilt0: { x: 26, y: 245, w: 24, h: 28 },
    wilt1: { x: 51, y: 245, w: 24, h: 28 },
    poof0: { x: 76, y: 245, w: 24, h: 28 },
    poof1: { x: 101, y: 245, w: 24, h: 28 },
    poof2: { x: 126, y: 245, w: 24, h: 28 },
  },
  azure: {
    idle0: { x: 151, y: 245, w: 24, h: 28 },
    idle1: { x: 176, y: 245, w: 24, h: 28 },
    walk0: { x: 201, y: 245, w: 24, h: 28 },
    walk1: { x: 226, y: 245, w: 24, h: 28 },
    walk2: { x: 1, y: 274, w: 24, h: 28 },
    walk3: { x: 26, y: 274, w: 24, h: 28 },
    work0: { x: 51, y: 274, w: 24, h: 28 },
    work1: { x: 76, y: 274, w: 24, h: 28 },
    carry0: { x: 101, y: 274, w: 24, h: 28 },
    carry1: { x: 126, y: 274, w: 24, h: 28 },
    blocked0: { x: 151, y: 274, w: 24, h: 28 },
    sleep0: { x: 176, y: 274, w: 24, h: 28 },
    sleep1: { x: 201, y: 274, w: 24, h: 28 },
    wilt0: { x: 226, y: 274, w: 24, h: 28 },
    wilt1: { x: 1, y: 303, w: 24, h: 28 },
    poof0: { x: 126, y: 42, w: 24, h: 28 },
    poof1: { x: 151, y: 42, w: 24, h: 28 },
    poof2: { x: 176, y: 42, w: 24, h: 28 },
  },
  gold: {
    idle0: { x: 26, y: 303, w: 24, h: 28 },
    idle1: { x: 51, y: 303, w: 24, h: 28 },
    walk0: { x: 76, y: 303, w: 24, h: 28 },
    walk1: { x: 101, y: 303, w: 24, h: 28 },
    walk2: { x: 126, y: 303, w: 24, h: 28 },
    walk3: { x: 151, y: 303, w: 24, h: 28 },
    work0: { x: 176, y: 303, w: 24, h: 28 },
    work1: { x: 201, y: 303, w: 24, h: 28 },
    carry0: { x: 226, y: 303, w: 24, h: 28 },
    carry1: { x: 1, y: 332, w: 24, h: 28 },
    blocked0: { x: 26, y: 332, w: 24, h: 28 },
    sleep0: { x: 51, y: 332, w: 24, h: 28 },
    sleep1: { x: 76, y: 332, w: 24, h: 28 },
    wilt0: { x: 101, y: 332, w: 24, h: 28 },
    wilt1: { x: 126, y: 332, w: 24, h: 28 },
    poof0: { x: 126, y: 42, w: 24, h: 28 },
    poof1: { x: 151, y: 42, w: 24, h: 28 },
    poof2: { x: 176, y: 42, w: 24, h: 28 },
  },
};

// prettier-ignore
export const ACCESSORY_FRAMES: Record<GardenVariant, AtlasFrame | null> = {
  green: null,
  teal: null,
  amber: null,
  dusk: null,
  onyx: null,
  azure: null,
  gold: null,
};

// Body-local top-left where the accessory overlay sits (head upper-left rim,
// beside the sprout). Single source of truth for the renderer + contact sheet.
// prettier-ignore
export const ACCESSORY_ANCHOR = { x: 3, y: 7 } as const;

// prettier-ignore
export type GardenAnimationName = 'idle' | 'walk' | 'work' | 'carry' | 'blocked' | 'sleep' | 'poof' | 'seed' | 'germinate' | 'wilt' | 'seedSink';

// prettier-ignore
export const ANIMATIONS: Record<GardenAnimationName, { frames: GardenFrameName[]; fps: number }> = {
  idle: { frames: ['idle0', 'idle0', 'idle0', 'idle0', 'idle0', 'idle0', 'idle0', 'idle1'], fps: 2 },
  walk: { frames: ['walk0', 'walk1', 'walk2', 'walk3'], fps: 6 },
  work: { frames: ['work0', 'work1'], fps: 3 },
  carry: { frames: ['carry0', 'carry1'], fps: 6 },
  blocked: { frames: ['blocked0'], fps: 1 },
  sleep: { frames: ['sleep0', 'sleep1'], fps: 1 },
  poof: { frames: ['poof0', 'poof1', 'poof2'], fps: 8 },
  seed: { frames: ['seed0', 'seed1'], fps: 1 },
  germinate: { frames: ['germinate0', 'germinate1', 'germinate2'], fps: 6 },
  wilt: { frames: ['wilt0', 'wilt1'], fps: 1 },
  seedSink: { frames: ['seedSink0', 'seedSink1'], fps: 4 },
};

// --- Biome ground-decoration tile sets (VUH-494) ---------------------------
// Grouped handles for VUH-495 to scatter decoration by biome. Every listed name
// is a GardenFrameName with a rect in ATLAS_FRAMES; these are props (never
// variant-tinted). `anchors` are the larger centerpiece tiles (a tidepool, a
// grassy patch); `tiles` are the small scatterable decorations.
// prettier-ignore
export const BIOME_TILE_SETS = {
  meadow: { tiles: ['meadowTuft', 'meadowTuftTall', 'meadowClover', 'meadowDaisy', 'meadowPebbles'], anchors: [] },
  tide: { tiles: ['tideStone', 'tideStoneSm', 'tideLily', 'tideReed', 'tideRipple'], anchors: ['tidePool'] },
  fern: { tiles: ['fernFrond', 'fernPair', 'fernMoss', 'fernShoot'], anchors: ['fernClump'] },
  sunflower: { tiles: ['sunflowerHead', 'sunflowerBud', 'sunflowerStalk', 'sunflowerSprout'], anchors: ['sunflowerTall'] },
  mushroom: { tiles: ['mushroomCap', 'mushroomPair', 'mushroomTiny', 'mushroomSpores'], anchors: ['mushroomCluster'] },
  rock: { tiles: ['rockStone', 'rockStoneSm', 'rockRaked', 'rockCairn'], anchors: ['rockBoulder'] },
  compost: { tiles: ['compostLeaf', 'compostLitter', 'compostTwig', 'compostMound'], anchors: ['compostHeap'] },
  shared: { tiles: ['pathWorn'], anchors: [] },
} as const;

export type GardenBiomeName = keyof typeof BIOME_TILE_SETS;

// --- Skill totems (VUH-621 / VUH-518) + lead badge (VUH-538) ----------------
// Real frozen art retiring the procedural placeholders. `totem` is one carved
// silhouette; a per-skill glyph from SKILL_GLYPH_FRAMES overlays its cream face at
// TOTEM_GLYPH_ANCHOR (body-local). GardenCanvas picks the glyph per skill by seed
// — floor(seed * SKILL_GLYPH_FRAMES.length) — the same deterministic seed path
// totemAccent() uses, so the art is frozen while the mapping stays data-driven.
// `leadCrown` is the gold circlet a per-run lead wears at LEAD_CROWN_ANCHOR.
// prettier-ignore
export const TOTEM_GLYPH_ANCHOR = { x: 5, y: 10 } as const;
// prettier-ignore
export const LEAD_CROWN_ANCHOR = { x: 6, y: 7 } as const;

// Ordered skill-glyph vocabulary (index by seed). Every name is a GardenFrameName
// with a rect in ATLAS_FRAMES.
// prettier-ignore
export const SKILL_GLYPH_FRAMES = ['skillStar', 'skillBolt', 'skillEye', 'skillArrow', 'skillDrop', 'skillLeaf', 'skillRing'] as const;

export type GardenSkillGlyphName = (typeof SKILL_GLYPH_FRAMES)[number];

// Palette and variant recolors remain pack data so the future SkinPack contract
// can consume the generated manifest without importing the authoring scripts.
export type GardenRgba = readonly [number, number, number, number];

// prettier-ignore
export const PALETTE = {
  "o": [80, 59, 44, 255],
  "k": [223, 221, 182, 255],
  "K": [178, 174, 126, 255],
  "f": [242, 229, 200, 255],
  "d": [227, 211, 174, 255],
  "m": [128, 100, 64, 255],
  "e": [38, 47, 58, 255],
  "p": [243, 178, 164, 255],
  "l": [198, 214, 104, 255],
  "g": [125, 143, 65, 255],
  "s": [111, 95, 54, 255],
  "b": [79, 59, 28, 255],
  "w": [232, 236, 228, 255],
  "W": [185, 192, 180, 255],
  "D": [107, 81, 56, 255],
  "E": [87, 66, 46, 255],
  "q": [110, 111, 102, 255],
  "Q": [138, 139, 128, 255],
  "y": [242, 229, 200, 255],
  "t": [99, 208, 189, 255],
  "T": [52, 152, 140, 255],
  "a": [240, 178, 74, 255],
  "u": [183, 156, 226, 255],
  "U": [125, 92, 176, 255],
  "n": [156, 164, 168, 255],
  "N": [103, 112, 116, 255],
  "r": [201, 163, 78, 255],
  "c": [60, 125, 114, 255],
  "C": [41, 80, 73, 255],
  "v": [85, 104, 79, 255],
  "V": [61, 76, 57, 255],
  "G": [198, 138, 58, 255],
  "H": [156, 107, 44, 255],
} as const satisfies Record<string, GardenRgba>;

// prettier-ignore
export const VARIANT_TINTS = {
  "green": null,
  "teal": {
    "l": [
      99,
      208,
      189,
      255
    ],
    "g": [
      52,
      152,
      140,
      255
    ]
  },
  "amber": {
    "l": [
      240,
      178,
      74,
      255
    ],
    "g": [
      196,
      122,
      44,
      255
    ]
  },
  "dusk": {
    "l": [
      183,
      156,
      226,
      255
    ],
    "g": [
      125,
      92,
      176,
      255
    ]
  },
  "onyx": {
    "l": [
      157,
      167,
      177,
      255
    ],
    "g": [
      44,
      49,
      56,
      255
    ],
    "recolor": {
      "o": [
        21,
        24,
        28,
        255
      ],
      "e": [
        21,
        24,
        28,
        255
      ],
      "K": [
        44,
        49,
        56,
        255
      ],
      "s": [
        44,
        49,
        56,
        255
      ],
      "m": [
        64,
        71,
        79,
        255
      ],
      "k": [
        90,
        99,
        108,
        255
      ],
      "d": [
        125,
        135,
        145,
        255
      ],
      "p": [
        125,
        135,
        145,
        255
      ],
      "f": [
        157,
        167,
        177,
        255
      ],
      "W": [
        125,
        135,
        145,
        255
      ],
      "w": [
        187,
        196,
        204,
        255
      ]
    }
  },
  "azure": {
    "l": [
      143,
      201,
      255,
      255
    ],
    "g": [
      74,
      115,
      184,
      255
    ]
  },
  "gold": {
    "l": [
      240,
      214,
      150,
      255
    ],
    "g": [
      201,
      163,
      78,
      255
    ]
  }
} as const;

// prettier-ignore
export const GARDEN_BACKGROUND = '#242a2e';
